-- Retired: do not create or restore MFA pauses.
-- Resume existing owner protection through admin Settings > Security with a real TOTP.
-- The protected enforce_store_mfa RPC removes only the current owner pause after AAL2 verification.
