begin;
alter table public.products add column if not exists photos jsonb not null default '[]'::jsonb;
create table if not exists public.store_admins (user_id uuid primary key references auth.users(id) on delete cascade);
alter table public.store_admins enable row level security;
revoke all on public.store_admins from anon, authenticated;
grant select on public.store_admins to authenticated;
drop policy if exists "Admins read own membership" on public.store_admins;
create policy "Admins read own membership" on public.store_admins for select to authenticated using(user_id=(select auth.uid()));
alter table public.products enable row level security;
-- The existing public read policy was inspected before migration.
drop policy if exists "Public can view products" on public.products;
drop policy if exists "Catalog available products" on public.products;
drop policy if exists "Admins read inventory" on public.products;
drop policy if exists "Admins add products" on public.products;
drop policy if exists "Admins edit products" on public.products;
grant select on public.products to anon,authenticated;
grant insert,update on public.products to authenticated;
revoke insert,update,delete on public.products from anon;
revoke delete on public.products from authenticated;
create policy "Catalog available products" on public.products for select to anon,authenticated using (available=true);
create policy "Admins read inventory" on public.products for select to authenticated using (exists(select 1 from public.store_admins where user_id=(select auth.uid())));
create policy "Admins add products" on public.products for insert to authenticated with check (exists(select 1 from public.store_admins where user_id=(select auth.uid())));
create policy "Admins edit products" on public.products for update to authenticated using (exists(select 1 from public.store_admins where user_id=(select auth.uid()))) with check (exists(select 1 from public.store_admins where user_id=(select auth.uid())));
do $$ declare s text; begin s:=pg_get_serial_sequence('public.products','id'); if s is not null then execute format('grant usage,select on sequence %s to authenticated',s); end if; end $$;
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values('product-photos','product-photos',true,6291456,array['image/jpeg','image/png','image/webp']) on conflict(id) do update set public=true,file_size_limit=excluded.file_size_limit,allowed_mime_types=excluded.allowed_mime_types;
drop policy if exists "Admins upload product photos" on storage.objects;
create policy "Admins upload product photos" on storage.objects for insert to authenticated with check(bucket_id='product-photos' and (storage.foldername(name))[1]=(select auth.uid())::text and exists(select 1 from public.store_admins where user_id=(select auth.uid())));
drop policy if exists "Admins read product photo metadata" on storage.objects;
create policy "Admins read product photo metadata" on storage.objects for select to authenticated using(bucket_id='product-photos' and exists(select 1 from public.store_admins where user_id=(select auth.uid())));
create index if not exists products_available_created_idx on public.products(created_at desc,id desc) where available=true;
commit;
-- After creating the owner in Supabase Authentication, register the UUID:
-- insert into public.store_admins(user_id) values ('OWNER_AUTH_USER_UUID') on conflict do nothing;
