const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http');
const root=path.resolve(__dirname,'..'),out=process.env.QA_OUTPUT||'/tmp/juli-action-audit';fs.mkdirSync(out,{recursive:true});
const server=http.createServer((req,res)=>{let url=new URL(req.url,'http://localhost').pathname;if(url==='/')url='/index.html';const file=path.resolve(root,'.'+url);if(!file.startsWith(root+path.sep)){res.writeHead(403).end();return}fs.readFile(file,(err,data)=>{res.writeHead(err?404:200,{'Content-Type':({'.html':'text/html','.js':'text/javascript','.css':'text/css','.webp':'image/webp','.woff':'font/woff'})[path.extname(file)]||'application/octet-stream'});res.end(err?'Missing':data)})});
(async()=>{await new Promise(r=>server.listen(8773,r));const browser=await chromium.launch({executablePath:process.env.QA_BROWSER_BINARY||undefined,args:['--no-sandbox']});
for(const width of [390,1280]){
 const page=await browser.newPage({viewport:{width,height:900}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.addInitScript(()=>{window.__links=[];window.open=url=>window.__links.push(url)});
 let rows=[{id:1,brand:'Gucci',name:'Кроссовки',category:'Обувь',size:'40; 41',price:500,currency:'EUR',available:true,fulfillment_status:'in_stock',gender:'women'},{id:2,brand:'Chrome Hearts',name:'Худи',category:'Худи',size:'XXL; XL',price:900,currency:'EUR',available:true,fulfillment_status:'on_order',gender:'unisex'},{id:3,brand:'RIMOWA',name:'Чехол',category:'Аксессуары',size:'One Size',price:180,currency:'EUR',available:true,fulfillment_status:'in_stock',gender:'unisex',reserved:true}];
 let checkoutRequests=0,delayCheckout=0,delayLinked=0;
 await page.route('**/rest/v1/products?**',async r=>{const u=r.request().url();if(u.includes('id=in.')){checkoutRequests++;if(delayCheckout)await new Promise(x=>setTimeout(x,delayCheckout))}if(u.includes('id=eq.999')&&delayLinked)await new Promise(x=>setTimeout(x,delayLinked));await r.fulfill({json:u.includes('id=eq.999')?[]:rows})});
 await page.goto('http://localhost:8773/');await page.locator('.product').first().waitFor();
 await page.locator('[data-id="1"]').click();await page.locator('[data-action=add-cart]').click();assert.match(await page.locator('#sizeHint').innerText(),/выберите/);await page.locator('[data-size="40"]').click();
 await page.evaluate(()=>{for(let n=0;n<150;n++)document.querySelector('[data-action=add-cart]').click()});assert.equal(await page.evaluate(()=>cartCount()),1);
 await page.locator('#backProduct').click();await page.locator('[data-id="2"]').click();assert.deepEqual(await page.locator('[data-size]').allTextContents(),['XL','XXL']);await page.locator('[data-size="XL"]').click();await page.evaluate(()=>{for(let n=0;n<150;n++)document.querySelector('[data-action=add-cart]').click()});assert.equal(await page.evaluate(()=>cartCount()),2);
 await page.evaluate(()=>{for(let n=0;n<150;n++)document.querySelector('[data-action=wishlist]').click()});assert.equal(await page.evaluate(()=>state.favorites.size),1);await page.waitForTimeout(470);await page.locator('[data-action=wishlist]').click();assert.equal(await page.evaluate(()=>state.favorites.size),0);
 await page.evaluate(()=>{for(let n=0;n<150;n++)document.querySelector('[data-action=sourcing]').click()});await page.waitForTimeout(30);assert.equal(await page.evaluate(()=>window.__links.length),1);
 await page.locator('#backProduct').click();await page.locator('[data-tab=cart]').click();const before=checkoutRequests;delayCheckout=250;
 await page.evaluate(()=>{for(let n=0;n<150;n++)document.querySelector('[data-cart-action=checkout]').click()});await page.locator('#cartStatus').filter({hasText:'Заказ подготовлен'}).waitFor();assert.equal(checkoutRequests-before,1);assert.equal(await page.evaluate(()=>window.__links.length),2);
 await page.evaluate(()=>{for(let n=0;n<150;n++)document.querySelector('[data-cart-action=checkout]').click()});await page.locator('[data-cart-action=checkout]:not([disabled])').waitFor();assert.equal(await page.evaluate(()=>window.__links.length),2);
 // Editing/removing while verification is pending must never open an old order.
 await page.evaluate(()=>{checkoutCart();cart.splice(0,1);saveCart();renderCart()});await page.locator('#cartStatus').filter({hasText:'Корзина изменилась'}).waitFor();assert.equal(await page.evaluate(()=>window.__links.length),2);
 await page.evaluate(()=>{for(let n=0;n<150;n++)document.querySelector('[data-cart-action=plus]').click()});assert.equal(await page.evaluate(()=>cart[0].quantity),2);await page.waitForTimeout(370);
 await page.evaluate(()=>{openProduct(1);selectedSize='40';addToCart();setTab('cart')});
 await page.evaluate(()=>{for(let n=0;n<150;n++){const b=document.querySelector('[data-cart-action=remove]');if(b)b.click()}});assert.equal(await page.locator('.cart-item').count(),1);await page.waitForTimeout(370);await page.locator('[data-cart-action=remove]').click();assert.equal(await page.locator('.cart-empty').count(),1);
 delayLinked=250;await page.evaluate(()=>{openLinkedProduct(999);setTab('favorites')});await page.waitForTimeout(300);assert.equal(await page.locator('#productModal').isHidden(),true);assert.equal(await page.evaluate(()=>state.tab),'favorites');
 await page.locator('[data-tab=catalog]').click();await page.locator('[data-id="3"]').click();assert.equal(await page.locator('[data-action=add-cart]').isDisabled(),true);assert.equal(await page.evaluate(()=>cart.length),0);
 assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.deepEqual(errors,[]);await page.screenshot({path:out+'/audit-'+width+'.png'});await page.close();console.log(width+' PASS 150-click buy/wishlist/manager/checkout/quantity/delete, price-safe cart edits, stale navigation, reserved One Size, ordered sizes');
}
await browser.close();server.close()})().catch(e=>{console.error(e);server.close();process.exit(1)});
