const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http');
const root=path.resolve(__dirname,'..'),out=process.env.QA_OUTPUT||'/tmp/juli-admin-design';fs.mkdirSync(out,{recursive:true});
const types={'.html':'text/html','.js':'text/javascript','.css':'text/css','.webp':'image/webp','.woff':'font/woff'};
const server=http.createServer((req,res)=>{let p=new URL(req.url,'http://localhost').pathname;if(p==='/')p='/index.html';const file=path.resolve(root,'.'+p);if(!file.startsWith(root+path.sep)){res.writeHead(403).end();return}fs.readFile(file,(err,data)=>{res.writeHead(err?404:200,{'Content-Type':types[path.extname(file)]||'application/octet-stream'});res.end(err?'Missing':data)})});
const rows=[{id:42,brand:'Gucci',name:'Кроссовки',category:'Обувь',size:'40; 41',price:500,currency:'EUR',image_url:'https://juliproz-store.vercel.app/images/gucci-blackwhite-45.webp',photos:[],available:true,fulfillment_status:'in_stock',gender:'women',revision:1},{id:43,brand:'Chrome Hearts',name:'Zip Hoodie',category:'Одежда',size:'XL; XXL',price:1800,currency:'EUR',available:true,fulfillment_status:'on_order',gender:'unisex',reserved:true,revision:1},{id:44,brand:'RIMOWA',name:'Чехол',category:'Аксессуары',size:'One Size',price:180,currency:'EUR',available:false,fulfillment_status:'in_stock',gender:'unisex',revision:1}];
(async()=>{await new Promise(r=>server.listen(8775,r));const browser=await chromium.launch({executablePath:process.env.QA_BROWSER_BINARY||undefined,args:['--no-sandbox']});
for(const width of [320,390,768,1280,1920]){
 const page=await browser.newPage({viewport:{width,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));let analyticsFail=false,delay=0,reads=0;
 await page.route('**/rest/v1/products?**',r=>r.fulfill({json:rows}));
 await page.route('https://juliproz-store.vercel.app/images/**',r=>{const file=path.join(root,new URL(r.request().url()).pathname);return fs.existsSync(file)?r.fulfill({contentType:'image/webp',body:fs.readFileSync(file)}):r.fulfill({status:404,body:''})});
 await page.route('**/rest/v1/rpc/store_analytics_summary',async r=>{reads++;if(delay)await new Promise(x=>setTimeout(x,delay));return analyticsFail?r.fulfill({status:503,json:{error:'offline'}}):r.fulfill({json:{active:3,visitors:18,sessions:24,wishlist_add:7,cart_add:5,products:[{id:42,brand:'Gucci',name:'Кроссовки',views:8,wishlist:3,cart:2}]}})});
 const fit=async()=>assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`${width} overflow`);
 await page.goto('http://localhost:8775/admin.html');await page.waitForTimeout(750);await page.screenshot({path:`${out}/admin-${width}-login.png`,fullPage:true});await fit();assert.equal(await page.locator('.admin-logo').textContent(),'J.P');assert.equal(await page.evaluate(()=>getComputedStyle(document.querySelector('.admin-header')).backgroundColor),'rgb(108, 144, 185)');
 await page.evaluate(rows=>{session={access_token:'synthetic',expires_at:Date.now()/1000+3600,user:{id:'synthetic'}};items=rows;$('authArea').classList.add('hidden');$('workspace').classList.remove('hidden');$('securityState').textContent='Вход защищён кодом из приложения.';render();refreshOverview()},rows);await page.waitForFunction(()=>$('overviewActive').textContent==='3');assert.equal(await page.locator('#overviewVisitors').textContent(),'18');await fit();await page.waitForTimeout(750);await page.screenshot({path:`${out}/admin-${width}-catalog.png`,fullPage:true});
 await page.locator('#productsMenuToggle').click();assert.equal(await page.locator('#productsMenuToggle').getAttribute('aria-expanded'),'false');assert.equal(await page.evaluate(()=>$('productNavigation').inert),true);await page.locator('#productsMenuToggle').click();await page.locator('.nav-child[data-view=reserved]').click();assert.equal(await page.locator('#inventory article').count(),1);await page.locator('.nav-child[data-view=all]').click();await page.locator('#categoryFilter').selectOption('Обувь');assert.equal(await page.locator('#inventory article').count(),1);await page.locator('#resetFilters').click();assert.equal(await page.locator('#inventory article').count(),3);
 await page.locator('.sidebar [data-view=settings]').click();assert.equal(await page.locator('#settingsPanel').isVisible(),true);assert.equal(await page.locator('#inventoryPanel').isHidden(),true);assert.equal(await page.locator('#securityBtn').count(),1);assert.equal(await page.locator('#settingsPanel #securityBtn').count(),1);await fit();await page.waitForTimeout(750);await page.screenshot({path:`${out}/admin-${width}-settings.png`,fullPage:true});
 await page.locator('#settingsAutoPhoto').uncheck();await page.locator('#settingsMotion').check();assert.equal(await page.evaluate(()=>document.body.classList.contains('reduce-motion')),true);await page.locator('#newProduct').click();assert.equal(await page.locator('#autoPhotoStyle').isChecked(),false);assert.equal(await page.locator('#settingsPanel').isHidden(),true);assert.equal(await page.evaluate(()=>getComputedStyle(document.querySelector('#editor')).animationName),'none');await fit();await page.waitForTimeout(750);await page.screenshot({path:`${out}/admin-${width}-editor.png`,fullPage:true});await page.locator('#cancel').click();
 await page.locator('.sidebar [data-view=analytics]').click();await page.locator('#analyticsStatus').filter({hasText:'Обновлено'}).waitFor();assert.equal(await page.locator('#analyticsCards .stat').count(),10);await fit();await page.waitForTimeout(750);await page.screenshot({path:`${out}/admin-${width}-analytics.png`,fullPage:true});
 if(width<=700){await page.locator('#adminMenuToggle').click();assert.equal(await page.locator('#adminMenuToggle').getAttribute('aria-expanded'),'false');assert.equal(await page.evaluate(()=>$('adminSidebar').inert),true);await page.locator('#adminMenuToggle').click();assert.equal(await page.evaluate(()=>$('adminSidebar').inert),false)}
 await page.reload();assert.equal(await page.locator('#settingsAutoPhoto').isChecked(),false);assert.equal(await page.locator('#settingsMotion').isChecked(),true);
 await page.evaluate(()=>{session={access_token:'synthetic',expires_at:Date.now()/1000+3600,user:{id:'synthetic'}};$('authArea').classList.add('hidden');$('workspace').classList.remove('hidden')});
 delay=150;const before=reads;await page.evaluate(()=>{for(let n=0;n<150;n++)refreshOverview()});await page.waitForFunction(()=>overviewBusy===false);assert.equal(reads-before,1);
 analyticsFail=true;await page.evaluate(()=>refreshOverview());await page.waitForFunction(()=>overviewBusy===false);assert.equal(await page.locator('#overviewActive').textContent(),'—');analyticsFail=false;
 await page.evaluate(()=>{refreshOverview();endSession()});await page.waitForTimeout(250);assert.equal(await page.locator('#overviewActive').textContent(),'—');assert.equal(await page.locator('#workspace').isHidden(),true);assert.deepEqual(errors,[]);await page.close();console.log(width+' PASS brand palette/fonts, card filters, animated/inert navigation, settings/security placement, preferences persistence, overview singleflight/error/logout guards, responsive pages');
}
await browser.close();server.close()})().catch(e=>{console.error(e);server.close();process.exit(1)});
