const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http');
const root=path.resolve(__dirname,'..'),out=process.env.QA_OUTPUT||'/tmp/juli-admin-design';fs.mkdirSync(out,{recursive:true});
const types={'.html':'text/html','.js':'text/javascript','.css':'text/css','.webp':'image/webp','.woff':'font/woff'};
const server=http.createServer((req,res)=>{let p=new URL(req.url,'http://localhost').pathname;if(p==='/')p='/index.html';const file=path.resolve(root,'.'+p);if(!file.startsWith(root+path.sep)){res.writeHead(403).end();return}fs.readFile(file,(err,data)=>{res.writeHead(err?404:200,{'Content-Type':types[path.extname(file)]||'application/octet-stream'});res.end(err?'Missing':data)})});
const rows=[{id:42,brand:'Gucci',name:'Кроссовки',category:'Обувь',size:'40; 41',price:500,currency:'EUR',image_url:'https://juliproz-store.vercel.app/images/gucci-blackwhite-45.webp',photos:[],available:true,fulfillment_status:'in_stock',gender:'women',revision:1},{id:43,brand:'Chrome Hearts',name:'Zip Hoodie',category:'Одежда',size:'XL; XXL',price:1800,currency:'EUR',available:true,fulfillment_status:'on_order',gender:'unisex',reserved:true,revision:1},{id:44,brand:'RIMOWA',name:'Чехол',category:'Аксессуары',size:'One Size',price:180,currency:'EUR',available:false,fulfillment_status:'in_stock',gender:'unisex',revision:1}];
(async()=>{await new Promise(r=>server.listen(8775,r));const browser=await chromium.launch({executablePath:process.env.QA_BROWSER_BINARY||undefined,args:['--no-sandbox']});
for(const width of [320,390,768,1280,1920]){
 const page=await browser.newPage({viewport:{width,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));let analyticsFail=false,delay=0,reads=0;
 await page.route('**/rest/v1/rpc/store_product_wishlist_counts',r=>r.fulfill({json:{days:30,counts:{42:9}}}));
 await page.route('**/rest/v1/products?**',r=>r.fulfill({json:rows}));
 await page.route('https://juliproz-store.vercel.app/images/**',r=>{const file=path.join(root,new URL(r.request().url()).pathname);return fs.existsSync(file)?r.fulfill({contentType:'image/webp',body:fs.readFileSync(file)}):r.fulfill({status:404,body:''})});
 await page.route('**/rest/v1/rpc/store_analytics_health',r=>r.fulfill({json:false}));await page.route('**/rest/v1/rpc/store_analytics_summary',async r=>{reads++;if(delay)await new Promise(x=>setTimeout(x,delay));return analyticsFail?r.fulfill({status:503,json:{error:'offline'}}):r.fulfill({json:{active:3,visitors:18,sessions:24,wishlist_add:7,cart_add:5,products:[{id:42,brand:'Gucci',name:'Кроссовки',views:8,wishlist:3,cart:2}]}})});
 const fit=async()=>assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`${width} overflow`);
 await page.goto('http://localhost:8775/admin.html');await page.waitForTimeout(750);await page.screenshot({path:`${out}/admin-${width}-login.png`,fullPage:true});await fit();assert.equal(await page.locator('.admin-logo').textContent(),'J.P');assert.equal(await page.evaluate(()=>getComputedStyle(document.querySelector('.admin-header')).backgroundColor),'rgb(108, 144, 185)');
 await page.evaluate(rows=>{session={access_token:'synthetic',expires_at:Date.now()/1000+3600,user:{id:'synthetic'}};items=rows;$('authArea').classList.add('hidden');$('workspace').classList.remove('hidden');$('securityState').textContent='Вход защищён кодом из приложения.';render();refreshOverview()},rows);await page.waitForFunction(()=>$('overviewActive').textContent==='3');assert.equal(await page.locator('#overviewVisitors').textContent(),'18');await page.waitForFunction(()=>productWishlistCounts!==null);assert.match(await page.locator('[data-product-wishlist="42"]').textContent(),/9 в вишлист/);assert.equal(await page.locator('#adminNavPaw').count(),0);
 await page.locator('#adminHome').click();assert.equal(await page.locator('#homePanel').isVisible(),true);await page.locator('#homePanel [data-view=all]').click();
 await page.evaluate(()=>{items=Array.from({length:18},(_,i)=>({...items[i%3],id:i===0?42:1000+i}));render();scrollTo(0,0)});const beforeTop=await page.locator('#adminSidebar').evaluate(el=>el.getBoundingClientRect().top);await page.evaluate(()=>scrollTo(0,200));const moved=await page.evaluate(()=>scrollY);assert.ok(moved>0);assert.equal(Math.round(beforeTop-await page.locator('#adminSidebar').evaluate(el=>el.getBoundingClientRect().top)),Math.round(moved));await page.evaluate(rows=>{items=rows;render();scrollTo(0,0)},rows);
 const actions=page.locator('#inventory article').first().locator('details');assert.equal(await actions.locator('.row-actions').isHidden(),true);await actions.locator('summary').click();await page.locator('[data-preview="42"]').click();assert.equal(await page.locator('#cataloguePreview').isVisible(),true);assert.equal(await page.locator('.catalogue-preview-card h3').textContent(),'Gucci');assert.equal(await page.locator('.catalogue-preview-price').textContent(),'€ 500');await page.keyboard.press('Escape');assert.equal(await page.locator('#cataloguePreview').isVisible(),false);
 await page.locator('[data-edit="42"]').click();await page.locator('[name=name]').fill('Gucci Новая модель');await page.locator('#previewCatalogue').click();assert.equal(await page.locator('.catalogue-preview-card p').textContent(),'Новая модель');await page.locator('#closeCataloguePreview').click();page.once('dialog',d=>d.dismiss());await page.locator('#adminHome').click();assert.equal(await page.locator('#editor').isVisible(),true);page.once('dialog',d=>d.accept());await page.locator('#adminHome').click();assert.equal(await page.locator('#homePanel').isVisible(),true);await page.locator('#homePanel [data-view=all]').click();await fit();await page.waitForTimeout(750);await page.screenshot({path:`${out}/admin-${width}-catalog.png`,fullPage:true});
 await page.locator('#productsMenuToggle').click();assert.equal(await page.locator('#productsMenuToggle').getAttribute('aria-expanded'),'false');assert.equal(await page.evaluate(()=>$('productNavigation').inert),true);await page.locator('#productsMenuToggle').click();await page.locator('.nav-child[data-view=reserved]').click();assert.equal(await page.locator('#inventory article').count(),1);await page.locator('.nav-child[data-view=all]').click();await page.locator('.admin-select-trigger').filter({hasText:'Все категории'}).click();await page.locator('#categoryFilter-options [role=option]').filter({hasText:'Обувь'}).click();assert.equal(await page.locator('#inventory article').count(),1);await page.locator('.nav-child[data-view=hidden]').click();assert.equal(await page.locator('#categoryFilter').inputValue(),'');assert.equal(await page.locator('#inventory article').count(),1);await page.locator('.nav-child[data-view=all]').click();await page.locator('#resetFilters').click();assert.equal(await page.locator('#inventory article').count(),3);
 await page.locator('.sidebar [data-view=settings]').click();assert.equal(await page.locator('#settingsPanel').isVisible(),true);assert.equal(await page.locator('#inventoryPanel').isHidden(),true);assert.equal(await page.locator('#securityBtn').count(),1);assert.equal(await page.locator('#settingsPanel #securityBtn').count(),1);await fit();await page.waitForTimeout(750);await page.screenshot({path:`${out}/admin-${width}-settings.png`,fullPage:true});
 await page.locator('#settingsAutoPhoto').uncheck();await page.locator('#settingsMotion').check();assert.equal(await page.evaluate(()=>document.body.classList.contains('reduce-motion')),true);await page.locator('#newProduct').click();assert.equal(await page.locator('#autoPhotoStyle').isChecked(),false);assert.equal(await page.locator('#settingsPanel').isHidden(),true);assert.equal(await page.evaluate(()=>getComputedStyle(document.querySelector('#editor')).animationName),'none');await fit();await page.waitForTimeout(750);await page.screenshot({path:`${out}/admin-${width}-editor.png`,fullPage:true});await page.locator('#cancel').click();
 await page.locator('.sidebar [data-view=analytics]').click();await page.locator('#analyticsStatus').filter({hasText:'Обновлено'}).waitFor();assert.equal(await page.locator('#analyticsCards .stat').count(),10);await fit();await page.waitForTimeout(750);await page.screenshot({path:`${out}/admin-${width}-analytics.png`,fullPage:true});
 if(width<=700){await page.locator('#adminMenuToggle').click();assert.equal(await page.locator('#adminMenuToggle').getAttribute('aria-expanded'),'false');assert.equal(await page.evaluate(()=>$('adminSidebar').inert),true);await page.locator('#adminMenuToggle').click();assert.equal(await page.evaluate(()=>$('adminSidebar').inert),false)}
 await page.reload();assert.equal(await page.locator('#settingsAutoPhoto').isChecked(),false);assert.equal(await page.locator('#settingsMotion').isChecked(),true);
 await page.evaluate(()=>{session={access_token:'synthetic',expires_at:Date.now()/1000+3600,user:{id:'synthetic'}};$('authArea').classList.add('hidden');$('workspace').classList.remove('hidden')});
 delay=150;const before=reads;await page.evaluate(()=>{for(let n=0;n<150;n++)refreshOverview()});await page.waitForFunction(()=>overviewBusy===false);assert.equal(reads-before,1);
 analyticsFail=true;await page.evaluate(()=>refreshOverview());await page.waitForFunction(()=>overviewBusy===false);assert.equal(await page.locator('#overviewActive').textContent(),'—');analyticsFail=false;
 await page.evaluate(()=>{refreshOverview();endSession()});await page.waitForTimeout(250);assert.equal(await page.locator('#overviewActive').textContent(),'—');assert.equal(await page.locator('#workspace').isHidden(),true);assert.deepEqual(errors,[]);await page.close();console.log(width+' PASS shared scroll/home/dropdown/preview/wishlist counters/no click paw, brand palette/fonts, card filters, animated/inert navigation, settings/security placement, preferences persistence, overview singleflight/error/logout guards, responsive pages');
}
// Exercise the real form, persisted browser storage, repeated reload and tab reopening.
// Save per-size quantities and reopen the card, then verify unit-based overview.
const quantityPage=await browser.newPage({viewport:{width:390,height:844}});let quantityRow={...rows[0],stock_quantities:null,product_condition:'new'},quantityWrite=null,quantityReadFails=false;
await quantityPage.route('https://qhgzzhgxwpcctafpzjid.supabase.co/**',route=>{if(new URL(route.request().url()).pathname==='/rest/v1/product_admin_notes')return route.fulfill({json:[]});if(new URL(route.request().url()).pathname==='/rest/v1/products'){if(route.request().method()==='PATCH'){quantityWrite=route.request().postDataJSON();quantityRow={...quantityRow,...quantityWrite,revision:quantityRow.revision+1};return route.fulfill({json:[quantityRow]})}if(quantityReadFails)return route.fulfill({status:503,json:{message:'offline'}});return route.fulfill({json:[quantityRow]})}return route.fulfill({json:{counts:{}}})});
await quantityPage.goto('http://localhost:8775/admin.html');await quantityPage.evaluate(p=>{session={access_token:'synthetic',expires_at:Date.now()/1000+3600,user:{id:'synthetic'}};items=[p];$('workspace').classList.remove('hidden');$('authArea').classList.add('hidden');edit(p)},quantityRow);
await quantityPage.locator('[name=original_price]').fill('400');await quantityPage.locator('#save').click();await quantityPage.locator('#status').filter({hasText:'Цена до скидки должна'}).waitFor();assert.equal(quantityWrite,null);await quantityPage.locator('[name=original_price]').fill('625');assert.equal(await quantityPage.locator('#previewPrice .discount-badge').textContent(),'−20%');await quantityPage.locator('[name=on_commission]').check();await quantityPage.locator('[data-quantity-size="40"]').fill('5');await quantityPage.locator('[data-quantity-size="41"]').fill('0');await quantityPage.locator('#save').click();await quantityPage.locator('#status').filter({hasText:'Товар сохранён'}).waitFor();assert.deepEqual(quantityWrite.stock_quantities,{'40':5,'41':0});assert.equal(quantityWrite.on_commission,true);assert.equal(quantityWrite.original_price,625);await quantityPage.locator('[data-view=sale]').click();assert.equal(await quantityPage.locator('#inventory article').count(),1);assert.equal(await quantityPage.locator('#inventory .discount-badge').textContent(),'−20%');await quantityPage.locator('[data-view=all]').first().click();assert.equal(await quantityPage.locator('#stockCount .sr-only').textContent(),'5');await quantityPage.evaluate(()=>edit(items[0]));assert.equal(await quantityPage.locator('[name=on_commission]').isChecked(),true);assert.equal(await quantityPage.locator('[name=original_price]').inputValue(),'625');assert.equal(await quantityPage.locator('#previewPrice .price-original').textContent(),'€ 625');assert.equal(await quantityPage.locator('[data-quantity-size="40"]').inputValue(),'5');assert.equal(await quantityPage.locator('[data-quantity-size="41"]').inputValue(),'0');await quantityPage.locator('[name=original_price]').fill('');quantityReadFails=true;await quantityPage.locator('[name=name]').fill('Сохранено при сбое списка');await quantityPage.locator('#save').click();await quantityPage.locator('#status').filter({hasText:'Не удалось обновить список'}).waitFor();assert.equal(await quantityPage.locator('#editor').isHidden(),true);assert.match(await quantityPage.locator('#inventory').textContent(),/Сохранено при сбое списка/);assert.equal(await quantityPage.evaluate(()=>editorDirty),false);assert.equal(quantityWrite.original_price,null);assert.equal(await quantityPage.locator('#inventory .discount-badge').count(),0);assert.equal(await quantityPage.evaluate(()=>matchesView({...items[0],stock_quantities:{'40':0,'41':0}},'in_stock')),false);assert.equal(await quantityPage.evaluate(()=>inventoryAvailability({...items[0],stock_quantities:{'40':0,'41':0}})),'Нет остатка');assert.equal(await quantityPage.evaluate(()=>matchesView({...items[0],available:false,reserved:true},'reserved')),false);await quantityPage.close();console.log('PASS size quantities save/reopen, zero balance and unit-based stock overview');
// Exercise the eraser on a white interior separated from the exterior by a product edge.
const eraserPage=await browser.newPage();await eraserPage.route('**/rest/v1/products?**',r=>r.fulfill({json:[]}));await eraserPage.goto('http://localhost:8775/admin.html');
await eraserPage.evaluate(async()=>{const c=document.createElement('canvas');c.width=c.height=100;const ctx=c.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,100,100);ctx.fillStyle='#503020';ctx.fillRect(20,20,60,60);ctx.fillStyle='#fff';ctx.fillRect(35,35,30,30);const blob=await new Promise(r=>c.toBlob(r,'image/png'));window.eraserEntry=await PhotoStudio.process(new File([blob],'eraser-test.png',{type:'image/png'}),false);PhotoStudio.open(eraserEntry,entry=>window.eraserApplied=entry,()=>{});});
await eraserPage.locator('#studioTools summary').click();await eraserPage.locator('#studioBrush').selectOption('region');await eraserPage.locator('#studioMask').scrollIntoViewIfNeeded();const eraserBox=await eraserPage.locator('#studioMask').boundingBox();await eraserPage.locator('#studioMask').click({position:{x:eraserBox.width/2,y:eraserBox.height/2}});
const alphaAt=(page,x,y)=>page.evaluate(([x,y])=>document.getElementById('studioMask').getContext('2d').getImageData(x,y,1,1).data[3],[x,y]);
assert.equal(await alphaAt(eraserPage,50,50),0);assert.equal(await alphaAt(eraserPage,25,25),255);assert.equal(await alphaAt(eraserPage,5,5),255);
await eraserPage.locator('#studioUndo').click();assert.equal(await alphaAt(eraserPage,50,50),255);await eraserPage.locator('#studioBrush').selectOption('background');await eraserPage.locator('#studioBrushSize').fill('70');await eraserPage.locator('#studioBrushSoftness').fill('0');await eraserPage.locator('#studioProtectEnabled').check();await eraserPage.locator('#studioMask').click({position:{x:eraserBox.width/2,y:eraserBox.height/2}});assert.equal(await alphaAt(eraserPage,50,50),255);await eraserPage.locator('#studioProtectEnabled').uncheck();await eraserPage.locator('#studioMask').click({position:{x:eraserBox.width/2,y:eraserBox.height/2}});assert.equal(await alphaAt(eraserPage,50,50),0);assert.equal(await alphaAt(eraserPage,25,25),255);await eraserPage.locator('#studioUndo').click();assert.equal(await alphaAt(eraserPage,50,50),255);await eraserPage.locator('#studioBrush').selectOption('region');await eraserPage.locator('#studioMask').click({position:{x:eraserBox.width/2,y:eraserBox.height/2}});await eraserPage.locator('#studioApply').click();await eraserPage.locator('#photoStudio').waitFor({state:'hidden'});assert.equal(await eraserPage.evaluate(()=>eraserApplied.state.mask.getContext('2d').getImageData(50,50,1,1).data[3]),0);assert.equal(await eraserPage.evaluate(()=>eraserEntry.state.mask.getContext('2d').getImageData(50,50,1,1).data[3]),255);await eraserPage.close();console.log('PASS interior background eraser, product edge protection, undo and applied mask isolation');
const authContext=await browser.newContext(),authPage=await authContext.newPage();let refreshCalls=0;
const authSession={access_token:'synthetic-access',refresh_token:'synthetic-refresh',expires_in:3600,user:{id:'reload-owner',factors:[]}};
await authContext.route('https://qhgzzhgxwpcctafpzjid.supabase.co/**',route=>{const url=new URL(route.request().url());if(url.pathname==='/auth/v1/token'){if(url.searchParams.get('grant_type')==='refresh_token')refreshCalls++;return route.fulfill({json:authSession})}if(url.pathname==='/auth/v1/user')return route.fulfill({json:authSession.user});if(url.pathname==='/rest/v1/store_admins')return route.fulfill({json:[{user_id:'reload-owner'}]});if(url.pathname.endsWith('store_admin_security_status'))return route.fulfill({json:{paused:true}});if(url.pathname==='/rest/v1/products')return route.fulfill({json:rows});return route.fulfill({json:{counts:{}}})});
await authPage.goto('http://localhost:8775/admin.html');await authPage.locator('#login [name=email]').fill('fixture@example.com');await authPage.locator('#login [name=password]').fill('fixture-password');await authPage.locator('#login button[type=submit]').click();await authPage.locator('#workspace').waitFor({state:'visible'});
assert.ok(await authPage.evaluate(()=>JSON.parse(localStorage.getItem('jpAdminSessionV1')).refresh_token));
assert.ok(await authPage.locator('#stockTotal .stock-digit').count()>0);assert.equal(await authPage.locator('#stockTotal .sr-only').textContent(),String(rows.length));await authPage.waitForTimeout(1800);assert.equal(await authPage.locator('#stockTotal .stock-digit-strip').count(),0);assert.equal(await authPage.locator('#stockTotal .stock-number-finished').textContent(),String(rows.length));assert.equal(await authPage.locator('#stockTotal .stock-digit').count(),0);

for(let n=0;n<3;n++){await authPage.reload();await authPage.locator('#workspace').waitFor({state:'visible'});assert.equal(await authPage.locator('#login').isVisible(),false)}
assert.equal(refreshCalls,0);await authPage.screenshot({path:`${out}/admin-auth-after-reload.png`,fullPage:true});await authPage.close();const reopened=await authContext.newPage();await reopened.goto('http://localhost:8775/admin.html');await reopened.locator('#workspace').waitFor({state:'visible'});assert.equal(await reopened.locator('#login').isVisible(),false);await authContext.close();console.log('PASS real login form, 3 reloads and reopened tab preserve admin access');
const queryPage=await browser.newPage({viewport:{width:390,height:844}});let queryWrite;
await queryPage.route('https://qhgzzhgxwpcctafpzjid.supabase.co/**',route=>{if(new URL(route.request().url()).pathname==='/rest/v1/product_admin_notes')return route.fulfill({json:[]});if(new URL(route.request().url()).pathname==='/rest/v1/products'){if(route.request().method()==='PATCH'){queryWrite=route.request().postDataJSON();return route.fulfill({json:[{...rows[0],...queryWrite,revision:rows[0].revision+1}]})}return route.fulfill({json:rows})}return route.fulfill({json:{}})});
await queryPage.goto('http://localhost:8775/admin.html');await queryPage.evaluate(p=>{session={access_token:'synthetic',expires_at:Date.now()/1000+3600,user:{id:'synthetic'}};$('authArea').classList.add('hidden');$('workspace').classList.remove('hidden');edit({...p,price:100,original_price:150})},rows[0]);
await queryPage.locator('[name=price_on_request]').check();assert.equal(await queryPage.locator('[name=price]').isDisabled(),true);assert.equal(await queryPage.locator('[name=original_price]').isDisabled(),true);assert.equal(await queryPage.locator('#previewPrice').textContent(),'Цена по запросу');await queryPage.locator('#save').click();await queryPage.locator('#status').filter({hasText:'Товар сохранён'}).waitFor();assert.equal(queryWrite.price,null);assert.equal(queryWrite.original_price,null);
await queryPage.evaluate(p=>edit({...p,price:null,original_price:null}),rows[0]);assert.equal(await queryPage.locator('[name=price_on_request]').isChecked(),true);await queryPage.locator('[name=price_on_request]').uncheck();assert.equal(await queryPage.locator('[name=price]').isDisabled(),false);await queryPage.locator('[name=product_condition]').selectOption('pre_owned');await queryPage.locator('#wearConditionField').waitFor({state:'visible'});await queryPage.locator('[name=wear_condition]').selectOption('gently_used');await queryPage.locator('[name=price]').fill('120');assert.match(await queryPage.locator('#previewCondition').textContent(),/Небольшие следы носки/);await queryPage.locator('#save').click();await queryPage.locator('#status').filter({hasText:'Товар сохранён'}).waitFor();assert.equal(queryWrite.wear_condition,'gently_used');assert.equal({...rows[0],...queryWrite}.currency,'EUR');await queryPage.evaluate(p=>edit({...p,product_condition:'pre_owned',wear_condition:'gently_used'}),rows[0]);assert.equal(await queryPage.locator('[name=wear_condition]').inputValue(),'gently_used');await queryPage.locator('[name=product_condition]').selectOption('new');assert.equal(await queryPage.locator('#wearConditionField').isHidden(),true);assert.equal(await queryPage.locator('[name=wear_condition]').inputValue(),'');assert.equal(await queryPage.locator('select[name=currency]').count(),0);await queryPage.close();console.log('PASS price-on-request mode clears discount, saves null and restores correctly');


// Internal commission notes use a separate protected endpoint; errors preserve the editor draft.
const notePage=await browser.newPage({viewport:{width:390,height:844}});let noteProduct={...rows[0],on_commission:true},privateNote={product_id:rows[0].id,note:'Synthetic owner, private commission terms <script>',revision:1},failNote=false;const productWrites=[];
await notePage.route('https://qhgzzhgxwpcctafpzjid.supabase.co/**',route=>{const path=new URL(route.request().url()).pathname,method=route.request().method();if(path==='/rest/v1/product_admin_notes'){if(method==='PATCH'){if(failNote)return route.fulfill({status:503,json:{message:'offline'}});const payload=route.request().postDataJSON();privateNote={...privateNote,...payload,revision:privateNote.revision+1}}return route.fulfill({json:[privateNote]})}if(path==='/rest/v1/products'){if(method==='PATCH'){const payload=route.request().postDataJSON();productWrites.push(payload);noteProduct={...noteProduct,...payload,revision:noteProduct.revision+1}}return route.fulfill({json:[noteProduct]})}return route.fulfill({json:{}})});
await notePage.goto('http://localhost:8775/admin.html');await notePage.evaluate(p=>{session={access_token:'synthetic',expires_at:Date.now()/1000+3600,user:{id:'synthetic'}};$('authArea').classList.add('hidden');$('workspace').classList.remove('hidden');edit(p)},noteProduct);await notePage.waitForFunction(()=>!$('editor').elements.internal_note.disabled&&$('editor').elements.internal_note.value.startsWith('Synthetic owner'));assert.equal(await notePage.locator('#internalNoteCard').isVisible(),true);assert.ok(!(await notePage.locator('#previewName').textContent()).includes('Synthetic owner'));
await notePage.locator('[name=internal_note]').fill('Updated private note');await notePage.locator('#save').click();await notePage.locator('#status').filter({hasText:'Товар сохранён'}).waitFor();assert.equal(privateNote.note,'Updated private note');assert.ok(productWrites.every(p=>!Object.hasOwn(p,'internal_note')&&!Object.hasOwn(p,'note')));
await notePage.evaluate(p=>edit(p),noteProduct);await notePage.waitForFunction(()=>$('editor').elements.internal_note.value==='Updated private note');await notePage.locator('[name=internal_note]').fill('Retain this private draft');await notePage.locator('[name=price]').fill('510');failNote=true;await notePage.locator('#save').click();await notePage.locator('#status').filter({hasText:'внутренняя заметка не сохранена'}).waitFor();assert.equal(await notePage.locator('#editor').isVisible(),true);assert.equal(await notePage.locator('[name=internal_note]').inputValue(),'Retain this private draft');failNote=false;await notePage.locator('#save').click();await notePage.locator('#status').filter({hasText:'Товар сохранён'}).waitFor();assert.equal(privateNote.note,'Retain this private draft');
await notePage.evaluate(p=>edit(p),noteProduct);await notePage.waitForFunction(()=>!$('editor').elements.internal_note.disabled);assert.equal(await notePage.locator('[name=internal_note]').inputValue(),'Retain this private draft');await notePage.screenshot({path:out+'/admin-390-private-note.png',fullPage:true});
assert.equal(await notePage.locator('.editor-footer').evaluate(el=>getComputedStyle(el).position),'static');assert.equal(await notePage.locator('[name=internal_note]').evaluate(el=>getComputedStyle(el).fontSize),'16px');
const mobileCodec=await notePage.evaluate(async()=>{const original=HTMLCanvasElement.prototype.toBlob;HTMLCanvasElement.prototype.toBlob=function(cb,type,q){if(type==='image/webp'){cb(null);return}return original.call(this,cb,type,q)};window.createImageBitmap=undefined;const c=document.createElement('canvas');c.width=c.height=64;c.getContext('2d').fillRect(10,10,20,20);const source=await new Promise(r=>original.call(c,r,'image/png')),file=new File([source],'iphone-photo.png',{type:'image/png'}),blob=await preparePhoto(file),img=await PhotoCodec.decode(blob);const sample=document.createElement('canvas');sample.width=sample.height=64;sample.getContext('2d').drawImage(img,0,0);img.close();return {type:blob.type,alpha:sample.getContext('2d').getImageData(0,0,1,1).data[3]}});assert.deepEqual(mobileCodec,{type:'image/png',alpha:0});await notePage.close();console.log('PASS protected commission note save/reopen, no public payload, failure/retry draft retention; mobile PNG/decode fallback and unobstructed footer');

await browser.close();server.close()})().catch(e=>{console.error(e);server.close();process.exit(1)});
