const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),http=require('node:http'),path=require('node:path');
const root=path.resolve(__dirname,'..');const server=http.createServer((req,res)=>{const p=new URL(req.url,'http://localhost').pathname;const file=path.resolve(root,'.'+(p==='/'?'/index.html':p));if(!file.startsWith(root+path.sep))return res.writeHead(403).end();fs.readFile(file,(err,data)=>{res.writeHead(err?404:200,{'Content-Type':({'.html':'text/html','.js':'text/javascript','.css':'text/css'})[path.extname(file)]||'application/octet-stream'});res.end(err?'Missing':data)})});
(async()=>{await new Promise(r=>server.listen(8778,r));const browser=await chromium.launch({executablePath:process.env.QA_BROWSER_BINARY||undefined,args:['--no-sandbox']});
// External Telegram loading must never block the catalogue; reload can paint cache before data arrives.
const startupPage=await browser.newPage({viewport:{width:390,height:844}});
let releaseSdk,releaseCatalog,holdCatalog=false;
const sdkGate=new Promise(r=>releaseSdk=r),catalogGate=new Promise(r=>releaseCatalog=r);
await startupPage.route('https://telegram.org/**',async route=>{await sdkGate;return route.fulfill({contentType:'text/javascript',body:"window.Telegram={WebApp:{initDataUnsafe:{},ready(){window.__sdkReady=(window.__sdkReady||0)+1},expand(){}}}"})});
await startupPage.route('**/rest/v1/products?**',async route=>{if(holdCatalog)await catalogGate;return route.fulfill({json:holdCatalog?[]:[{id:100,brand:'Brand',name:'Fast catalogue',available:true,price:80,original_price:100,currency:'EUR'}]})});
await startupPage.goto('http://localhost:8778/',{waitUntil:'domcontentloaded'});
await startupPage.locator('[data-id="100"]').waitFor({timeout:3000});assert.equal(await startupPage.evaluate(()=>window.__sdkReady||0),0);
await startupPage.locator('.masthead-controls [data-sale]').click();assert.equal(await startupPage.locator('.masthead-controls [data-sale]').getAttribute('aria-pressed'),'true');assert.equal(await startupPage.locator('[data-id=100]').count(),1);assert.match(await startupPage.locator('#filterSummary').textContent(),/SALE/);await startupPage.locator('.masthead-controls [data-sale]').click();assert.equal(await startupPage.locator('.masthead-controls [data-sale]').getAttribute('aria-pressed'),'false');releaseSdk();await startupPage.waitForFunction(()=>window.__sdkReady===1);
holdCatalog=true;await startupPage.reload({waitUntil:'domcontentloaded'});await startupPage.locator('[data-id="100"]').waitFor({timeout:3000});
assert.equal(await startupPage.evaluate(()=>catalogLoading),true);releaseCatalog();await startupPage.waitForFunction(()=>products.length===0&&!catalogLoading);await startupPage.close();
console.log('PASS catalogue before Telegram SDK and cached reload before fresh inventory');
for(const width of [390,1280]){
 const page=await browser.newPage({viewport:{width,height:900}}),events=[],errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.route('https://telegram.org/**',r=>r.fulfill({contentType:'text/javascript',body:''}));
 await page.route('**/functions/v1/store-analytics',r=>{events.push(r.request().postDataJSON());return r.fulfill({status:202,json:{accepted:true}})});
 await page.route('**/rest/v1/products?**',r=>r.fulfill({json:[{id:1,brand:'Gucci',name:'Hoodie',size:'38,40',description:'Материал: хлопок\n<script>unsafe</script>',price:100,currency:'EUR',available:true,fulfillment_status:'in_stock',photos:[]}]}));
 await page.goto('http://localhost:8778/');await page.locator('.product-open').waitFor();assert.equal(events.length,0);assert.equal(await page.evaluate(()=>localStorage.getItem('jpAnalyticsVisitor')),null);await page.locator('#analyticsDecline').click();
 await page.locator('.product-open').focus();await page.keyboard.press('Enter');await page.locator('#productModal:not(.hidden)').waitFor();assert.deepEqual(await page.locator('[data-size]').allTextContents(),['38','40']);assert.match(await page.locator('.product-description').innerText(),/Материал: хлопок\n<script>/);assert.equal(await page.locator('#productContent script').count(),0);
 assert.equal(await page.evaluate(()=>document.activeElement.id),'backProduct');await page.keyboard.press('Shift+Tab');assert.equal(await page.evaluate(()=>document.getElementById('productModal').contains(document.activeElement)),true);await page.keyboard.press('Escape');assert.equal(await page.locator('#productModal').isHidden(),true);assert.equal(await page.evaluate(()=>document.activeElement.classList.contains('product-open')),true);
 await page.locator('#openCatalogMenu').click();await page.locator('#analyticsPreferences').click();await page.locator('#analyticsAccept').click();await page.waitForFunction(()=>localStorage.getItem('jpAnalyticsVisitor')!==null);await page.waitForTimeout(100);assert.ok(events.some(x=>x.event==='visit'));
 await page.evaluate(()=>StoreAnalytics.setConsent(false));const before=events.length;await page.evaluate(()=>StoreAnalytics.track('cart_add',1));await page.waitForTimeout(100);assert.equal(events.length,before);assert.equal(await page.evaluate(()=>localStorage.getItem('jpAnalyticsVisitor')),null);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 await page.goto('http://localhost:8778/admin.html');await page.evaluate(()=>{session={access_token:'synthetic',expires_at:Date.now()/1000+3600,user:{id:'synthetic'}};$('authArea').classList.add('hidden');$('workspace').classList.remove('hidden');edit({id:1,brand:'Gucci',name:'Hoodie',size:'38,40',price:100,currency:'EUR',photos:[],revision:1})});assert.equal(await page.locator('[name=currency]').inputValue(),'EUR');assert.equal(await page.locator('[name=size]').inputValue(),'38\n40');assert.deepEqual(errors,[]);await page.close();console.log(width+' PASS consent/no pre-consent identity/revoke, separated sizes/escaped description, keyboard dialog focus/Escape/restore, EUR editor');
}
await browser.close();server.close()})().catch(e=>{console.error(e);server.close();process.exit(1)});
