const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const nodes=new Map(),saved=new Map();const get=id=>{if(!nodes.has(id))nodes.set(id,{innerHTML:'',textContent:'',value:'',classList:{add(){},remove(){},toggle(){},contains(){return false}},addEventListener(){},setAttribute(){}});return nodes.get(id)};
let rows=[],fail=false,links=[];
const context=vm.createContext({ProductSizes:require('../product-sizes.js'),safeProductImage:()=>false,window:{STORE_CONFIG:{url:'https://test.invalid',key:'public'},open:u=>links.push(u),addEventListener(){}},document:{getElementById:get,querySelectorAll:()=>[],querySelector:()=>null,addEventListener(){}},localStorage:{getItem:k=>saved.get(k)||null,setItem:(k,v)=>saved.set(k,v)},location:{search:''},URLSearchParams,AbortSignal,setTimeout,fetch:async()=>{if(fail)throw Error();return {ok:true,json:async()=>rows}}});
vm.runInContext(fs.readFileSync(__dirname+'/../product-pricing.js','utf8'),context);
 vm.runInContext(fs.readFileSync(__dirname+'/../app.js','utf8'),context);const run=s=>vm.runInContext(s,context);
(async()=>{await new Promise(setImmediate);
rows=[{id:1,brand:'Gucci',name:'Обувь',size:'40; 41',price:100,original_price:125,currency:'EUR',fulfillment_status:'on_order'},{id:2,brand:'Chanel',name:'Сумка',size:'',price:200,currency:'EUR',fulfillment_status:'on_order'}];context.fixture=rows;run('products=fixture;openProduct(1);addToCart()');assert.equal(run('cart.length'),0);
run("selectedSize='40';addToCart();addToCart();selectedSize='41';addToCart();openProduct(2);addToCart()");assert.equal(run('cart.length'),3);assert.equal(run('cartCount()'),3);assert.match(get('cartContent').innerHTML,/−20%/);assert.match(get('cartContent').innerHTML,/price-original/);assert.equal(run('readCart().length'),3);assert.deepEqual(JSON.parse(run('JSON.stringify(cartTotals().totals)')),[{currency:'EUR',price:400}]);
await run('checkoutCart()');assert.equal(links.length,1);assert.match(decodeURIComponent(links[0]),/размер 40 — 1 шт/);assert.match(decodeURIComponent(links[0]),/Итого: € 400/);
await run('checkoutCart()');assert.equal(links.length,1);assert.match(get('cartStatus').textContent,/Подождите/);
rows[0]={...rows[0],price:120};await run('checkoutCart()');assert.equal(links.length,1);assert.match(get('cartStatus').textContent,/изменились/);assert.equal(run('cartTotals().totals[0].price'),440);await run('checkoutCart()');assert.equal(links.length,2);
rows[0]={...rows[0],size:'40'};await run('checkoutCart()');assert.equal(links.length,2);assert.match(get('cartStatus').textContent,/недоступны/);
fail=true;await run('checkoutCart()');assert.equal(links.length,2);assert.equal(run('checkoutBusy'),false);assert.match(get('cartStatus').textContent,/Не удалось/);
run("toggleWishlist(2);state.tab='favorites';state.category='Обувь';state.search='не найдено'");assert.equal(run('filtered().length'),1);assert.equal(run('filtered()[0].id'),2);assert.equal(JSON.parse(saved.get('jpFav'))[0],'2');
saved.set('jpCart','{broken');assert.equal(run('readCart().length'),0);saved.set('jpCart',JSON.stringify([{id:'bad,query',size:'',quantity:100},{id:2,size:'',quantity:1000},{id:2,size:'',quantity:2}]));assert.equal(run('readCart().length'),1);assert.equal(run('readCart()[0].quantity'),99);
run("cart=[];products=[{id:7,brand:'Gucci',name:'Обувь',size:'40',price:100,currency:'EUR',fulfillment_status:'in_stock'}];openProduct(7);addToCart();addToCart()");assert.equal(run('cartCount()'),1);assert.match(get('shareStatus').textContent,/уже в корзине/);run('cart[0].quantity=9;renderCart()');assert.equal(run('cartCount()'),1);
// A still-open detail must not add a removed item or an obsolete size/price.
run("cart=[];products=[{id:8,name:'Товар',size:'40',price:100,currency:'EUR',fulfillment_status:'in_stock'}];openProduct(8);products=[];addToCart()");assert.equal(run('cart.length'),0);assert.match(get('shareStatus').textContent,/недоступен/);
run("products=[{id:8,name:'Товар',size:'40',price:100,currency:'EUR',fulfillment_status:'in_stock'}];openProduct(8);products=[{...products[0],size:'41'}];addToCart()");assert.equal(run('cart.length'),0);assert.match(get('shareStatus').textContent,/изменилась/);assert.equal(run('selectedSize'),'41');run('addToCart()');assert.equal(run('cart[0].size'),'41');
run("cart=[];openProduct(8);products=[{...products[0],price:120}];addToCart()");assert.equal(run('cart.length'),0);run('addToCart()');assert.equal(run('cart[0].product.price'),120);
// An unspecified-size cart row cannot skip a size added by the administrator.
fail=false;rows=[{id:9,name:'Товар',size:'',price:100,currency:'EUR',fulfillment_status:'in_stock'}];context.fixture=rows;run('cart=[];products=fixture;openProduct(9);addToCart()');rows=[{...rows[0],size:'42'}];const linksBefore=links.length;await run('checkoutCart()');assert.equal(links.length,linksBefore);assert.match(get('cartStatus').textContent,/недоступны/);assert.match(get('cartContent').innerHTML,/размер сейчас недоступен/);
run("products=[{id:1,category:'Обувь',brand:'Gucci',gender:'men'},{id:2,category:'Обувь',brand:'Gucci',gender:'unisex'},{id:3,category:'Сумки',brand:'Gucci'},{id:4,category:'Обувь',brand:'Gucci',available:false},{id:5,category:'Обувь',gender:'women'}]");assert.deepEqual(JSON.parse(run('JSON.stringify(relatedProducts(products[0]).map(x=>x.id))')),[2]);assert.match(run('relatedMarkup(products[0])'),/Похожие товары/);
// Reservation stays visible, prevents adding, and is checked again for old carts.
rows=[{id:11,name:'На брони',size:'',price:100,currency:'EUR',available:true,fulfillment_status:'in_stock',reserved:true}];context.fixture=rows;
run('cart=[];products=fixture;openProduct(11);addToCart()');assert.equal(run('cart.length'),0);assert.match(get('productContent').innerHTML,/На брони/);assert.match(get('productContent').innerHTML,/data-action="add-cart"[^>]*disabled/);assert.match(get('shareStatus').textContent,/на брони/);
rows=[{...rows[0],reserved:false}];context.fixture=rows;run('products=fixture;openProduct(11);addToCart()');assert.equal(run('cart.length'),1);
rows=[{...rows[0],reserved:true}];const beforeReservation=links.length;await run('checkoutCart()');assert.equal(links.length,beforeReservation);assert.match(get('cartStatus').textContent,/на брони/);assert.equal(run('cart[0].product.reserved'),true);
rows=[{...rows[0],reserved:false}];await run('checkoutCart()');assert.equal(links.length,beforeReservation+1);
run("cart=[];products=[]");rows=Array.from({length:30},(_,i)=>({id:1000+i,brand:'Brand',name:'N'.repeat(150),size:'',price:100,currency:'EUR',fulfillment_status:'in_stock'}));context.fixture=rows;run("products=fixture;for(const p of products){openProduct(p.id);addToCart()}");const beforeLarge=links.length;await run('checkoutCart()');assert.equal(links.length,beforeLarge);assert.match(get('cartStatus').textContent,/слишком большой/);
assert.equal(run("pluralRu(21,'товар','товара','товаров')"),'товар');assert.equal(run("pluralRu(22,'вещь','вещи','вещей')"),'вещи');assert.equal(run("pluralRu(112,'вещь','вещи','вещей')"),'вещей');
// Per-size stock caps additions and catches a reduced/zero balance before checkout.
run("cart=[];products=[{id:77,name:'Кепка',size:'One Size',available:true,price:100,currency:'EUR',fulfillment_status:'in_stock',stock_quantities:{'One Size':5}}];openProduct(77);addToCart();cart[0].quantity=9;renderCart()");assert.equal(run('cart[0].quantity'),5);assert.equal(run('cartLimit(products[0],"One Size")'),5);
rows=[{id:77,name:'Кепка',size:'One Size',available:true,price:100,currency:'EUR',fulfillment_status:'in_stock',stock_quantities:{'One Size':2}}];const beforeStockLinks=links.length;await run('checkoutCart()');assert.equal(links.length,beforeStockLinks);assert.equal(run('cart[0].quantity'),2);await run('checkoutCart()');assert.equal(links.length,beforeStockLinks+1);
rows=[{...rows[0],stock_quantities:{'One Size':0}}];await run('checkoutCart()');assert.equal(links.length,beforeStockLinks+1);assert.match(get('cartStatus').textContent,/недоступны/);
run("products=[{id:78,name:'Закончился',size:'One Size',available:true,fulfillment_status:'in_stock',stock_quantities:{'One Size':0}}];openProduct(78)");
assert.equal(run('availabilityLabel(products[0])'),'Нет в наличии');assert.match(get('productContent').innerHTML,/data-action="add-cart"[^>]*disabled/);
run("state.tab='catalog';state.fulfillment_status='in_stock';state.category=null;state.search='';state.product_condition=null");assert.equal(run('filtered().length'),0);
run("products[0].stock_quantities={'One Size':1}");assert.equal(run('filtered().length'),1);run('products[0].reserved=true');assert.equal(run('filtered().length'),0);
run("state.fulfillment_status=null;products[0].reserved=false;products[0].stock_quantities={'One Size':0};products[0].fulfillment_status='on_order';openProduct(78)");assert.equal(run('availabilityLabel(products[0])'),'Под заказ');assert.doesNotMatch(get('productContent').innerHTML,/data-action="add-cart"[^>]*disabled/);
run("products=[{id:1,available:true,price:80,original_price:100,product_condition:'pre_owned',brand:'Gucci',category:'Обувь'},{id:2,available:true,price:100,original_price:null,brand:'Chanel',category:'Сумки'},{id:3,available:true,price:100,original_price:80,brand:'Dior',category:'Сумки'}];state.sale=true;state.tab='catalog';state.fulfillment_status=null;state.product_condition=null;state.gender=null;state.category=null;state.brand=null;state.size=null;state.search=''");
assert.deepEqual(JSON.parse(run('JSON.stringify(filtered().map(p=>p.id))')),[1]);assert.deepEqual(JSON.parse(run('JSON.stringify(valuesFor("brand"))')),['Все','Gucci']);
run("state.product_condition='pre_owned'");assert.equal(run('filtered().length'),1);get('reset').onclick();assert.equal(run('state.sale'),false);assert.equal(run('filtered().length'),3);
// Sorting uses euro current prices, preserves catalogue order, and keeps missing prices last.
run("products=[{id:1,price:100,currency:'EUR',created_at:'2026-01-01'},{id:2,price:55,currency:'EUR',original_price:110,created_at:'2026-03-01'},{id:3,price:null,currency:'EUR',created_at:'2026-02-01'},{id:4,price:0,currency:'EUR',original_price:10}];state.sort='price_asc'");
assert.deepEqual(JSON.parse(run('JSON.stringify(filtered().map(p=>p.id))')),[4,2,1,3]);
run("state.sort='price_desc'");assert.deepEqual(JSON.parse(run('JSON.stringify(filtered().map(p=>p.id))')),[1,2,4,3]);
run("state.sort='newest'");assert.deepEqual(JSON.parse(run('JSON.stringify(filtered().map(p=>p.id))')),[2,3,1,4]);
run("state.sort='discount'");assert.deepEqual(JSON.parse(run('JSON.stringify(filtered().map(p=>p.id))')),[4,2,1,3]);assert.deepEqual(JSON.parse(run('JSON.stringify(products.map(p=>p.id))')),[1,2,3,4]);get('reset').onclick();assert.equal(run('state.sort'),'newest');
// Price sorting needs no exchange-rate request.
fail=true;await run("changeCatalogSort('price_asc')");assert.equal(run('state.sort'),'price_asc');assert.equal(get('sortStatus').textContent,'');fail=false;
assert.equal(run("money({price:100,currency:'USD'})"),'');
assert.match(run("conditionBadge({product_condition:'pre_owned',wear_condition:'gently_used'})"),/Небольшие следы носки/);
assert.equal(run("wearLabel({product_condition:'new',wear_condition:'used'})"),'');
// Static Sell and empty Cart must not access hidden catalogue card data.
run("cart=[];products=[{id:999,get name(){throw Error('Hidden catalogue was rendered')}}];setTab('sell');setTab('services');setTab('cart');state.favorites.clear();setTab('favorites')");assert.equal(run('state.tab'),'favorites');
console.log('PASS cart: sizes, quantities, euro totals, persistence, changed-price confirmation, unavailable sizes, network failures, wishlist independent of filters, corrupt storage');
})().catch(e=>{console.error(e);process.exitCode=1});
