const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const nodes=new Map(),saved=new Map();const get=id=>{if(!nodes.has(id))nodes.set(id,{innerHTML:'',textContent:'',value:'',classList:{add(){},remove(){},toggle(){}},addEventListener(){},setAttribute(){}});return nodes.get(id)};
let rows=[],fail=false,links=[];
const context=vm.createContext({ProductSizes:require('../product-sizes.js'),safeProductImage:()=>false,window:{STORE_CONFIG:{url:'https://test.invalid',key:'public'},open:u=>links.push(u),addEventListener(){}},document:{getElementById:get,querySelectorAll:()=>[],querySelector:()=>null,addEventListener(){}},localStorage:{getItem:k=>saved.get(k)||null,setItem:(k,v)=>saved.set(k,v)},location:{search:''},URLSearchParams,AbortSignal,setTimeout,fetch:async()=>{if(fail)throw Error();return {ok:true,json:async()=>rows}}});
vm.runInContext(fs.readFileSync(__dirname+'/../app.js','utf8'),context);const run=s=>vm.runInContext(s,context);
(async()=>{await new Promise(setImmediate);
rows=[{id:1,brand:'Gucci',name:'Обувь',size:'40; 41',price:100,currency:'EUR',fulfillment_status:'on_order'},{id:2,brand:'Chanel',name:'Сумка',size:'',price:200,currency:'USD',fulfillment_status:'on_order'}];context.fixture=rows;run('products=fixture;openProduct(1);addToCart()');assert.equal(run('cart.length'),0);
run("selectedSize='40';addToCart();addToCart();selectedSize='41';addToCart();openProduct(2);addToCart()");assert.equal(run('cart.length'),3);assert.equal(run('cartCount()'),4);assert.equal(run('readCart().length'),3);assert.deepEqual(JSON.parse(run('JSON.stringify(cartTotals().totals)')),[{currency:'EUR',price:300},{currency:'USD',price:200}]);
await run('checkoutCart()');assert.equal(links.length,1);assert.match(decodeURIComponent(links[0]),/размер 40 — 2 шт/);assert.match(decodeURIComponent(links[0]),/Итого: € 300 \+ \$ 200/);
rows[0]={...rows[0],price:120};await run('checkoutCart()');assert.equal(links.length,1);assert.match(get('cartStatus').textContent,/изменились/);assert.equal(run('cartTotals().totals[0].price'),360);await run('checkoutCart()');assert.equal(links.length,2);
rows[0]={...rows[0],size:'40'};await run('checkoutCart()');assert.equal(links.length,2);assert.match(get('cartStatus').textContent,/недоступны/);
fail=true;await run('checkoutCart()');assert.equal(links.length,2);assert.equal(run('checkoutBusy'),false);assert.match(get('cartStatus').textContent,/Не удалось/);
run("toggleWishlist(2);state.tab='favorites';state.category='Обувь';state.search='не найдено'");assert.equal(run('filtered().length'),1);assert.equal(run('filtered()[0].id'),2);assert.equal(JSON.parse(saved.get('jpFav'))[0],'2');
saved.set('jpCart','{broken');assert.equal(run('readCart().length'),0);saved.set('jpCart',JSON.stringify([{id:'bad,query',size:'',quantity:100},{id:2,size:'',quantity:1000},{id:2,size:'',quantity:2}]));assert.equal(run('readCart().length'),1);assert.equal(run('readCart()[0].quantity'),99);
run("cart=[];products=[{id:7,brand:'Gucci',name:'Обувь',size:'40',price:100,currency:'EUR',fulfillment_status:'in_stock'}];openProduct(7);addToCart();addToCart()");assert.equal(run('cartCount()'),1);assert.match(get('shareStatus').textContent,/уже в корзине/);run('cart[0].quantity=9;renderCart()');assert.equal(run('cartCount()'),1);
// A still-open detail must not add a removed item or an obsolete size/price.
run("cart=[];products=[{id:8,name:'Товар',size:'40',price:100,currency:'EUR',fulfillment_status:'in_stock'}];openProduct(8);products=[];addToCart()");assert.equal(run('cart.length'),0);assert.match(get('shareStatus').textContent,/недоступен/);
run("products=[{id:8,name:'Товар',size:'40',price:100,currency:'EUR',fulfillment_status:'in_stock'}];openProduct(8);products=[{...products[0],size:'41'}];addToCart()");assert.equal(run('cart.length'),0);assert.match(get('shareStatus').textContent,/изменилась/);assert.equal(run('selectedSize'),'41');run('addToCart()');assert.equal(run('cart[0].size'),'41');
run("cart=[];openProduct(8);products=[{...products[0],price:120}];addToCart()");assert.equal(run('cart.length'),0);run('addToCart()');assert.equal(run('cart[0].product.price'),120);
// An unspecified-size cart row cannot skip a size added by the administrator.
fail=false;rows=[{id:9,name:'Товар',size:'',price:100,currency:'EUR',fulfillment_status:'in_stock'}];context.fixture=rows;run('cart=[];products=fixture;openProduct(9);addToCart()');rows=[{...rows[0],size:'42'}];const linksBefore=links.length;await run('checkoutCart()');assert.equal(links.length,linksBefore);assert.match(get('cartStatus').textContent,/недоступны/);assert.match(get('cartContent').innerHTML,/размер сейчас недоступен/);
run("products=[{id:1,category:'Обувь',brand:'Gucci',gender:'men'},{id:2,category:'Обувь',brand:'Gucci',gender:'unisex'},{id:3,category:'Сумки',brand:'Gucci'},{id:4,category:'Обувь',brand:'Gucci',available:false},{id:5,category:'Обувь',gender:'women'}]");assert.deepEqual(JSON.parse(run('JSON.stringify(relatedProducts(products[0]).map(x=>x.id))')),[2]);assert.match(run('relatedMarkup(products[0])'),/Похожие товары/);
console.log('PASS cart: sizes, quantities, separate currencies, persistence, changed-price confirmation, unavailable sizes, network failures, wishlist independent of filters, corrupt storage');
})().catch(e=>{console.error(e);process.exitCode=1});
