const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http');
const root=path.resolve(__dirname,'..'),out=process.env.QA_OUTPUT||'/tmp/juli-final-edition';fs.mkdirSync(out,{recursive:true});
const server=http.createServer((req,res)=>{let url=new URL(req.url,'http://localhost').pathname;if(url==='/')url='/index.html';const file=path.resolve(root,'.'+url);if(!file.startsWith(root+path.sep)){res.writeHead(403).end();return}fs.readFile(file,(err,data)=>{res.writeHead(err?404:200,{'Content-Type':({'.html':'text/html','.js':'text/javascript','.css':'text/css','.webp':'image/webp','.woff':'font/woff'})[path.extname(file)]||'application/octet-stream'});res.end(err?'Missing':data)})});
(async()=>{await new Promise(r=>server.listen(8772,r));const browser=await chromium.launch({executablePath:process.env.QA_BROWSER_BINARY||undefined,args:['--no-sandbox']});
for(const width of [320,390,768,1280,1920]){
 const page=await browser.newPage({viewport:{width,height:width<500?844:900}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.addInitScript(()=>{window.open=url=>{window.__order=url}});
 let rows=[{id:99,brand:'Gucci',name:'Кроссовки',category:'Обувь',size:'40; 41',price:500,currency:'EUR',image_url:'https://juliproz-store.vercel.app/images/gucci-ace-bee-37-cover.webp',available:true,fulfillment_status:'in_stock',gender:'unisex',reserved:false},{id:100,brand:'Hermès',name:'Сумка',category:'Сумки',size:'One Size',price:900,currency:'EUR',image_url:'https://juliproz-store.vercel.app/images/gucci-ace-bee-37-cover.webp',available:true,fulfillment_status:'in_stock',gender:'women',reserved:true},{id:101,brand:'Test',name:'<img src=x onerror=alert(1)>',category:'Аксессуары',size:'XL',price:180,currency:'EUR',available:true,fulfillment_status:'on_order',gender:'men'}];
 await page.route('https://juliproz-store.vercel.app/images/**',r=>r.fulfill({path:root+'/images/gucci-ace-bee-37-cover.webp',contentType:'image/webp'}));await page.route('**/rest/v1/products?**',r=>r.fulfill({json:rows}));await page.goto('http://localhost:8772/');await page.locator('.product').first().waitFor();await page.evaluate(()=>document.fonts.ready);
 const settle=()=>page.evaluate(()=>Promise.all(document.getAnimations().map(a=>a.finished.catch(()=>{}))));const fits=()=>page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth);await settle();assert.ok(await fits());assert.equal(await page.locator('.product [onerror]').count(),0);
 await page.locator('[data-tab=favorites]').click();await settle();assert.equal(await page.locator('.wishlist-empty').count(),1);assert.equal(await page.locator('.wishlist-empty .empty-signature').textContent(),'J.P');assert.match(await page.locator('.wishlist-empty').innerText(),/сердечко/);await page.screenshot({path:out+'/wishlist-'+width+'.png',fullPage:true});assert.ok(await fits());
 await page.locator('[data-tab=cart]').click();await settle();assert.equal(await page.locator('.cart-empty').count(),1);const centered=await page.locator('.empty-content').evaluate(e=>{const r=e.getBoundingClientRect();return Math.abs(r.left+r.width/2-innerWidth/2)<2});assert.ok(centered);assert.equal(await page.locator('.cart-empty h2').textContent(),'Корзина');await page.screenshot({path:out+'/cart-empty-'+width+'.png',fullPage:true});assert.ok(await fits());await page.locator('[data-cart-action=catalog]').click();
 await page.locator('#openCatalogMenu').click();await settle();assert.equal(await page.locator('.menu-logo').textContent(),'J.P');assert.equal(await page.locator('#catalogMenu').getAttribute('class'),'catalog-menu');assert.equal(await page.locator('#catalogMenu').innerText().then(s=>s.includes('Ваш выбор')),false);assert.equal(await page.locator('.menu-paw').evaluate(i=>i.complete&&i.naturalWidth>0),true);assert.equal(await page.locator('.menu-choices').first().evaluate(e=>getComputedStyle(e).gridTemplateColumns.split(' ').length),2);assert.ok(await fits());await page.screenshot({path:out+'/menu-'+width+'.png',fullPage:true});
 // Modal keyboard boundary, gender/category-dependent sizes and reset.
 await page.locator('#resetMenu').focus();await page.keyboard.press('Tab');assert.equal(await page.locator('#closeCatalogMenu').evaluate(e=>e===document.activeElement),true);await page.keyboard.press('Escape');await page.locator('#catalogMenu').waitFor({state:'hidden'});assert.equal(await page.locator('#openCatalogMenu').evaluate(e=>e===document.activeElement),true);
 await page.locator('#openCatalogMenu').click();await page.locator('[data-gender=men]').click();assert.equal(await page.locator('.product').count(),2);await page.locator('[data-menu-type=category][data-menu-value="Аксессуары"]').click();assert.deepEqual(await page.locator('#menuChoices-size button').allTextContents(),['Все','XL']);await page.locator('#resetMenu').click();await page.locator('#showMenuProducts').click();await page.locator('[data-heart="99"]').click();await page.locator('[data-tab=favorites]').click();assert.equal(await page.locator('.wishlist-empty').count(),0);assert.equal(await page.locator('.product').count(),1);
 await page.locator('[data-id="99"]').click();await page.locator('[data-action=add-cart]').click();assert.match(await page.locator('#sizeHint').textContent(),/выберите/);await page.locator('[data-size="40"]').click();await page.locator('[data-action=add-cart]').click();await page.locator('#backProduct').click();await page.locator('[data-tab=cart]').click();assert.equal(await page.locator('.cart-empty').count(),0);assert.equal(await page.locator('.cart-item').count(),1);assert.equal(await page.locator('[data-cart-action=plus]').isDisabled(),true);await settle();await page.screenshot({path:out+'/cart-filled-'+width+'.png',fullPage:true});
 rows=rows.map(r=>r.id===99?{...r,reserved:true}:r);await page.locator('[data-cart-action=checkout]').click();await page.locator('#cartStatus').filter({hasText:'на брони'}).waitFor();assert.equal(await page.evaluate(()=>window.__order),undefined);rows=rows.map(r=>r.id===99?{...r,reserved:false}:r);await page.locator('[data-cart-action=checkout]').click();await page.locator('#cartStatus').filter({hasText:'Заказ подготовлен'}).waitFor();assert.match(await page.evaluate(()=>window.__order),/^https:\/\/t.me\/juliproz\?text=/);await page.locator('[data-cart-action=remove]').click();assert.equal(await page.locator('.cart-empty').count(),1);assert.ok(await fits());assert.deepEqual(errors,[]);await page.close();console.log(width+' PASS empty states, menu, keyboard, filters, escaping, wishlist, cart and revalidation');
}
await browser.close();server.close()})().catch(e=>{console.error(e);server.close();process.exit(1)});
