const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),http=require('node:http'),path=require('node:path');
const root=path.resolve(__dirname,'..');
const server=http.createServer((req,res)=>{let url=new URL(req.url,'http://localhost').pathname;if(url==='/')url='/index.html';const file=path.resolve(root,'.'+url);if(!file.startsWith(root+path.sep)){res.writeHead(403).end();return}fs.readFile(file,(err,data)=>{res.writeHead(err?404:200,{'Content-Type':({'.html':'text/html','.js':'text/javascript','.css':'text/css','.webp':'image/webp'})[path.extname(file)]||'application/octet-stream'});res.end(err?'Missing':data)})});
(async()=>{await new Promise(r=>server.listen(8771,r));const browser=await chromium.launch({executablePath:process.env.QA_BROWSER_BINARY||undefined,args:['--no-sandbox']});
for(const width of [390,400,1280]){
 const page=await browser.newPage({viewport:{width,height:900}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 const rows=[{id:99,brand:'Gucci',name:'Кроссовки',category:'Обувь',size:'40; 41',price:500,currency:'EUR',image_url:'https://juliproz-store.vercel.app/images/gucci-ace-bee-37-cover.webp',available:true,fulfillment_status:'in_stock',gender:'unisex',reserved:false},{id:100,brand:'Hermès',name:'Сумка',category:'Сумки',size:'One Size',price:900,currency:'EUR',image_url:'https://juliproz-store.vercel.app/images/gucci-ace-bee-37-cover.webp',available:true,fulfillment_status:'in_stock',gender:'women',reserved:true}];
 await page.route('https://juliproz-store.vercel.app/images/**',r=>r.fulfill({path:root+'/images/gucci-ace-bee-37-cover.webp',contentType:'image/webp'}));await page.route('**/rest/v1/products?**',r=>r.fulfill({json:rows}));await page.goto('http://localhost:8771/');await page.locator('.product').first().waitFor();await page.evaluate(()=>document.fonts.ready);await page.evaluate(()=>Promise.all(document.getAnimations().map(a=>a.finished.catch(()=>{}))));
 await page.locator('.photo img').first().waitFor();await page.locator('.photo img').first().evaluate(i=>i.decode());assert.equal(await page.locator('.brand #openCatalogMenu').count(),1);assert.equal(await page.locator('.brand #toggleSearch').count(),1);assert.equal(await page.locator('.brand-credit').count(),0);assert.equal(await page.locator('#brandPaw img').evaluate(i=>i.complete&&i.naturalWidth>0),true);
 assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:'/tmp/masthead-'+width+'.png',fullPage:false});
 await page.locator('#brandPaw').click();assert.equal(await page.locator('.brand').evaluate(e=>e.classList.contains('is-grabbing')),true);await page.locator('.brand').evaluate(e=>Promise.all(e.getAnimations({subtree:true}).map(a=>a.finished.catch(()=>{}))));
 await page.locator('#toggleSearch').click();await page.locator('#search').fill('Gucci');assert.equal(await page.locator('.product').count(),1);await page.locator('#search').fill('');
 await page.locator('#openCatalogMenu').click();await page.locator('#catalogMenu').waitFor({state:'visible'});assert.equal(await page.locator('.brand').evaluate(e=>e.inert),true);await page.locator('#closeCatalogMenu').click();await page.locator('#catalogMenu').waitFor({state:'hidden'});assert.equal(await page.locator('.brand').evaluate(e=>e.inert),false);
 await page.locator('[data-id="99"]').click();await page.locator('[data-size="40"]').click();await page.locator('[data-action="add-cart"]').click();await page.locator('#backProduct').click();await page.locator('[data-tab="cart"]').click();assert.equal(await page.locator('.cart-item').count(),1);for(const tab of ['favorites','catalog','cart']){await page.locator('[data-tab="'+tab+'"]').click();assert.equal(await page.locator('#navPaw').evaluate(e=>e.classList.contains('is-pressing')),true);assert.equal(await page.locator('[data-tab="'+tab+'"]').getAttribute('aria-current'),'page');assert.equal(await page.locator('[data-tab="'+tab+'"]').evaluate(e=>getComputedStyle(e,'::after').content),'none');}
 await page.locator('#navPaw').evaluate(e=>{const a=e.getAnimations()[0];a.pause();a.currentTime=330});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:'/tmp/nav-paw-'+width+'.png',fullPage:false});await page.locator('#navPaw').evaluate(e=>e.getAnimations()[0]?.finish());await page.emulateMedia({reducedMotion:'reduce'});await page.locator('[data-tab="catalog"]').click();assert.equal(await page.locator('#navPaw').isVisible(),false);assert.deepEqual(errors,[]);await page.close();console.log(width+' PASS masthead, paw, menu, search, cards and cart');
}
await browser.close();server.close()})().catch(e=>{console.error(e);server.close();process.exit(1)});
