const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),http=require('node:http'),path=require('node:path');
const root=path.resolve(__dirname,'..');
const server=http.createServer((req,res)=>{let p=new URL(req.url,'http://localhost').pathname;if(p==='/')p='/index.html';const file=path.resolve(root,'.'+p);if(!file.startsWith(root+path.sep)){res.writeHead(403).end();return}fs.readFile(file,(err,data)=>{res.writeHead(err?404:200,{'Content-Type':({'.html':'text/html','.js':'text/javascript','.css':'text/css','.webp':'image/webp'})[path.extname(file)]||'application/octet-stream'});res.end(err?'Missing':data)})});
(async()=>{await new Promise(r=>server.listen(8774,r));const browser=await chromium.launch({executablePath:process.env.QA_BROWSER_BINARY||undefined,args:['--no-sandbox']});
for(const width of [390,1280]){
 const page=await browser.newPage({viewport:{width,height:900}}),errors=[],events=[];page.on('pageerror',e=>errors.push(e.message));
 await page.route('**/functions/v1/store-analytics',r=>{events.push(r.request().postDataJSON());return r.fulfill({status:202,json:{accepted:true}})});
 await page.route('**/rest/v1/products?**',r=>r.fulfill({json:[]}));
 await page.goto('http://localhost:8774/');await page.waitForTimeout(150);
 await page.evaluate(()=>{for(let i=0;i<150;i++)StoreAnalytics.track('wishlist_add',42)});await page.waitForTimeout(100);assert.equal(events.filter(x=>x.event==='wishlist_add').length,1);assert.equal(events.filter(x=>x.event==='visit').length,1);assert.ok(events.every(x=>!('telegram_id'in x)&&!('name'in x)));
 let queries=0;await page.route('**/rest/v1/rpc/store_analytics_summary',async r=>{queries++;assert.equal(r.request().headers().authorization,'Bearer synthetic');await new Promise(x=>setTimeout(x,80));return r.fulfill({json:{active:2,visitors:7,sessions:8,wishlist_add:3,cart_add:4,products:[{id:42,brand:'Gucci',name:'<script>bad</script>',views:5,wishlist:3,cart:4}]}})});
 await page.goto('http://localhost:8774/admin.html');await page.evaluate(()=>{session={access_token:'synthetic',expires_at:Date.now()/1000+3600,user:{id:'synthetic'}};$('authArea').classList.add('hidden');$('workspace').classList.remove('hidden');render()});
 await page.locator('[data-view=analytics]').click();await page.locator('#analyticsStatus').filter({hasText:'Обновлено'}).waitFor();assert.equal(await page.locator('#analyticsCards .stat').count(),10);assert.equal(await page.locator('#analyticsProducts script').count(),0);await page.evaluate(()=>{for(let i=0;i<150;i++)$('refreshAnalytics').click()});await page.locator('#refreshAnalytics:not([disabled])').waitFor();assert.equal(queries,2);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 await page.locator('[data-view=all]').first().click();await page.evaluate(()=>edit({id:42,brand:'Gucci',name:'Фото',image_url:'https://juliproz-store.vercel.app/images/test-photo.png',photos:['https://juliproz-store.vercel.app/images/test-photo-2.png']}));
 const png=await page.evaluate(()=>{const c=document.createElement('canvas');c.width=400;c.height=300;const ctx=c.getContext('2d');ctx.fillStyle='white';ctx.fillRect(0,0,400,300);ctx.fillStyle='#224466';ctx.fillRect(100,50,200,200);return c.toDataURL('image/png').split(',')[1]});
 await page.route('**/images/test-photo*.png',r=>r.fulfill({contentType:'image/png',body:Buffer.from(png,'base64')}));
 // First fetch fails: the entire original gallery stays available.
 await page.route('**/images/test-photo-2.png',r=>r.fulfill({status:500,body:'error'}));await page.locator('#styleExistingPhotos').click();await page.locator('#status').filter({hasText:'Исходные фото сохранены'}).waitFor();assert.equal(await page.evaluate(()=>photos.length),2);assert.equal(await page.evaluate(()=>pendingPreviews.length),0);
 await page.unroute('**/images/test-photo-2.png');await page.locator('#styleExistingPhotos').click();await page.locator('#status').filter({hasText:'Фото оформлены'}).waitFor();assert.equal(await page.evaluate(()=>photos.length),0);assert.equal(await page.evaluate(()=>pendingPreviews.length),2);assert.equal(await page.evaluate(()=>pendingPreviews[0].name), 'product-42-1.png');assert.equal(await page.evaluate(()=>pendingPreviews.every(p=>p.state.background==='transparent'&&p.state.padding===8)),true);
 const pixels=await page.evaluate(async()=>{const p=pendingPreviews[0];const image=new Image();image.src=p.src;await image.decode();const c=document.createElement('canvas');c.width=c.height=1400;const ctx=c.getContext('2d');ctx.drawImage(image,0,0);return [image.width,image.height,ctx.getImageData(0,0,1,1).data[3],ctx.getImageData(700,700,1,1).data[3]]});assert.deepEqual(pixels,[1400,1400,0,255]);
 await page.locator('[data-studio="0"]').click();await page.locator('#studioApply').click();await page.waitForFunction(()=>pendingPreviews[0].reviewed===true);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.deepEqual(errors,[]);await page.close();console.log(width+' PASS analytics dedup/admin singleflight/escaping/layout and existing-photo batch rollback/order/transparent preset/review');
}
await browser.close();server.close()})().catch(e=>{console.error(e);server.close();process.exit(1)});
