const {chromium}=require('playwright');
const fs=require('node:fs'),http=require('node:http'),path=require('node:path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'),cfg=JSON.parse(fs.readFileSync(root+'/vercel.json'));
const mime={'.js':'text/javascript','.mjs':'text/javascript','.wasm':'application/wasm','.css':'text/css','.html':'text/html','.webp':'image/webp'};
const server=http.createServer((req,res)=>{const route=new URL(req.url,'http://localhost').pathname;let file=root+route;const header=cfg.headers.find(h=>h.source==='/photo-worker.js'&&route==='/photo-worker.js')||cfg.headers.find(h=>h.source==='/(admin|admin.html|admin/)'&&route==='/admin.html')||cfg.headers[0];for(const h of header.headers)res.setHeader(h.key,h.value);fs.readFile(file,(err,data)=>{res.writeHead(err?404:200,{'Content-Type':mime[path.extname(file)]||'application/octet-stream'});res.end(err?'Missing':data)});});
(async()=>{await new Promise(r=>server.listen(8766,r));const browser=await chromium.launch({headless:true,executablePath:process.env.QA_BROWSER_BINARY||undefined,args:['--no-sandbox','--no-zygote','--disable-dev-shm-usage','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});const page=await browser.newPage({viewport:{width:1440,height:1000}});page.setDefaultTimeout(120000);const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')console.log('BROWSER',m.text().slice(0,300))});
await page.goto('http://localhost:8766/admin.html');await page.evaluate(()=>{session={access_token:'synthetic',user:{id:'synthetic'},expires_at:Date.now()/1000+3600};document.getElementById('authArea').classList.add('hidden');document.getElementById('workspace').classList.remove('hidden');edit(null)});
console.time('process');await page.locator('#uploads').setInputFiles(root+'/images/gucci-blackwhite-45.webp');await page.waitForFunction(()=>!busy&&pendingPreviews.length===1);console.timeEnd('process');console.log(await page.locator('#status').textContent());assert.equal(await page.evaluate(()=>!!pendingPreviews[0].state),true,'real model should produce editable result');assert.equal(await page.evaluate(()=>$('uploads').files[0].name.endsWith('-juli.webp')),true);
const metrics=await page.evaluate(async()=>{const b=await createImageBitmap($('uploads').files[0]);const c=document.createElement('canvas');c.width=b.width;c.height=b.height;c.getContext('2d').drawImage(b,0,0);const d=c.getContext('2d').getImageData(0,0,c.width,c.height).data;let clear=0,opaque=0;for(let i=3;i<d.length;i+=4){if(d[i]===0)clear++;if(d[i]>200)opaque++}return {width:b.width,height:b.height,clear,opaque}});assert.equal(metrics.width,1400);assert.equal(metrics.height,1400);assert.ok(metrics.clear>10000&&metrics.opaque>10000);console.log('MASK',metrics);
await page.locator('[data-studio="0"]').click();await page.locator('#photoStudio').waitFor({state:'visible'});await page.screenshot({path:path.join(process.env.QA_OUTPUT||'/tmp','photo-studio-desktop.png'),fullPage:true});await page.locator('#studioBackground').selectOption('#eeebe6');await page.locator('#studioRotate').click();await page.locator('#studioApply').click();await page.locator('#photoStudio').waitFor({state:'hidden'});assert.equal(await page.evaluate(()=>pendingPreviews[0].state.rotation),90);assert.equal(await page.evaluate(()=>pendingPreviews[0].state.background),'#eeebe6');
await page.locator('[data-studio="0"]').click();await page.locator('#studioTools').click();await page.locator('#studioBrush').selectOption('restore');const box=await page.locator('#studioMask').boundingBox();await page.mouse.move(box.x+box.width/2,box.y+box.height/2);await page.mouse.down();await page.mouse.move(box.x+box.width/2+10,box.y+box.height/2+10);await page.mouse.up();await page.locator('#studioApply').click();await page.locator('#photoStudio').waitFor({state:'hidden'});
await page.locator('[data-studio="0"]').click();await page.locator('#studioOriginal').click();assert.equal(await page.evaluate(()=>$('uploads').files[0].name),'gucci-blackwhite-45.webp');assert.equal(await page.evaluate(()=>pendingPreviews[0].state),undefined);
await page.locator('#autoPhotoStyle').uncheck();await page.locator('#uploads').setInputFiles(root+'/images/gucci-blackwhite-45.webp');await page.waitForFunction(()=>!busy);assert.equal(await page.evaluate(()=>pendingPreviews[0].state),undefined);
await page.locator('[data-studio="0"]').click();await page.locator('#photoStudio').waitFor({state:'visible'});await page.setViewportSize({width:390,height:844});assert.ok(await page.evaluate(()=>document.querySelector('#photoStudio').scrollWidth<=document.querySelector('#photoStudio').clientWidth));await page.screenshot({path:path.join(process.env.QA_OUTPUT||'/tmp','photo-studio-mobile.png'),fullPage:true});await page.keyboard.press('Escape');assert.equal(await page.locator('#photoStudio').isVisible(),false);
await page.locator('[data-pending-remove="0"]').click();assert.equal(await page.evaluate(()=>$('uploads').files.length),0);
// Exercise actual inference with an opaque, non-uniform background (no simple-mask fast path).
const inference=await page.evaluate(async()=>{const image=new Image();image.src='/images/gucci-blackwhite-45.webp';await image.decode();const canvas=document.createElement('canvas');canvas.width=700;canvas.height=700;const ctx=canvas.getContext('2d'),gradient=ctx.createLinearGradient(0,0,700,700);gradient.addColorStop(0,'#b7c4ce');gradient.addColorStop(1,'#ead8c2');ctx.fillStyle=gradient;ctx.fillRect(0,0,700,700);ctx.drawImage(image,40,40,620,620);ctx.fillStyle='#b7c4ce';ctx.fillRect(0,0,30,30);ctx.fillStyle='#ead8c2';ctx.fillRect(670,670,30,30);const blob=await new Promise(r=>canvas.toBlob(r,'image/png'));const result=await PhotoStudio.process(new File([blob],'raw-photo.png',{type:'image/png'}));return {size:result.file.size,width:result.state.mask.width,background:result.state.background}});assert.ok(inference.size>1000);console.log('INFERENCE',inference);
// Save the processed bytes and URL through the existing upload/card pipeline using an isolated API fixture.
let uploaded=null,saved=null;
await page.route('**/storage/v1/object/product-photos/**',route=>{uploaded={type:route.request().headers()['content-type'],body:route.request().postDataBuffer()};return route.fulfill({json:{Key:'fixture'}})});
await page.route('**/rest/v1/products?**',route=>{const req=route.request();if(req.method()==='POST'){saved={...req.postDataJSON(),id:900010,revision:1};return route.fulfill({json:[saved]})}return route.fulfill({json:req.url().includes('creation_key=')?[]:saved?[saved]:[]})});
await page.locator('#uploads').setInputFiles(root+'/images/gucci-blackwhite-45.webp');await page.waitForFunction(()=>!busy&&pendingPreviews.length===1);await page.locator('[data-studio="0"]').click();await page.locator('#photoStudio').waitFor({state:'visible'});await page.locator('#studioApply').click();await page.locator('#photoStudio').waitFor({state:'hidden'});
await page.locator('[name=brand]').fill('Gucci');await page.locator('[name=name]').fill('Тестовое фото');await page.locator('[name=category]').fill('Обувь');await page.locator('#save').click();await page.locator('#status').filter({hasText:'Товар сохранён'}).waitFor();assert.equal(uploaded.type,'image/webp');assert.ok(uploaded.body.length>1000);assert.match(saved.image_url,/product-photos\/synthetic\/.+\.webp$/);assert.equal(saved.photos[0],saved.image_url);
assert.deepEqual(errors,[]);await browser.close();server.close();console.log('PASS real WASM inference with production CSP, preview, apply, brush, original restore, auto-off, retry, mobile, Escape, removal');})().catch(e=>{console.error(e);server.close();process.exit(1)});
