const {clickAdminAction}=require('./admin-action-helper.cjs');
const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),http=require('node:http'),path=require('node:path');
const root=path.resolve(__dirname,'..');
const types={'.html':'text/html','.js':'text/javascript','.css':'text/css','.webp':'image/webp','.woff2':'font/woff2'};
const server=http.createServer((req,res)=>{let pathname=new URL(req.url,'http://localhost').pathname;if(pathname==='/')pathname='/index.html';const file=path.resolve(root,'.'+pathname);if(!file.startsWith(root+path.sep)){res.writeHead(403).end();return}fs.readFile(file,(err,data)=>{res.writeHead(err?404:200,{'Content-Type':types[path.extname(file)]||'application/octet-stream'});res.end(err?'Missing':data)})});
(async()=>{await new Promise(r=>server.listen(8770,r));const browser=await chromium.launch({executablePath:process.env.QA_BROWSER_BINARY||undefined,args:['--no-sandbox','--disable-dev-shm-usage']});
for(const width of [390,1280]){
 const page=await browser.newPage({viewport:{width,height:900}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 let row={id:991,brand:'Gucci',name:'Кроссовки',category:'Обувь',size:'40',price:500,currency:'EUR',image_url:'/images/gucci-blackwhite-45.webp',photos:[],available:true,fulfillment_status:'in_stock',gender:'unisex',revision:1,reserved:false},inventory=[row],calls=[];
 await page.route('**/rest/v1/rpc/store_product_wishlist_counts',r=>r.fulfill({json:{days:30,counts:{}}}));
 await page.route('**/rest/v1/rpc/store_analytics_summary',r=>r.fulfill({json:{active:0,visitors:0}}));
 await page.route('**/rest/v1/products?**',route=>{const req=route.request();calls.push(req.method());if(req.method()==='PATCH'){assert.ok(req.url().includes('revision=eq.'+row.revision));row={...row,...req.postDataJSON(),revision:row.revision+1};inventory=[row];return route.fulfill({json:inventory})}if(req.method()==='DELETE'){const deleted=inventory;inventory=[];return route.fulfill({json:deleted})}return route.fulfill({json:inventory})});
 await page.goto('http://localhost:8770/admin.html');await page.evaluate(row=>{session={access_token:'synthetic',expires_at:Date.now()/1000+3600,user:{id:'synthetic'}};items=[row];$('authArea').classList.add('hidden');$('workspace').classList.remove('hidden');render()},row);
 await clickAdminAction(page,'[data-reserve="991"]');await page.locator('#status').filter({hasText:'Товар на брони'}).waitFor();assert.equal(row.reserved,true);assert.equal(row.available,true);assert.equal(await page.locator('[data-reserve="991"]').textContent(),'Снять бронь');await page.locator('.sidebar [data-view="reserved"]').click();assert.equal(await page.locator('#inventory article').count(),1);
 assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:path.join(process.env.QA_OUTPUT||'/tmp','reservation-admin-'+width+'.png'),fullPage:true});
 await clickAdminAction(page,'[data-edit="991"]');assert.equal(await page.locator('[name=reserved]').isChecked(),true);assert.equal(await page.locator('[name=available]').isChecked(),true);await page.locator('#cancel').click();await clickAdminAction(page,'[data-reserve="991"]');await page.locator('#status').filter({hasText:'Бронь снята'}).waitFor();assert.equal(row.reserved,false);await page.locator('[data-view="all"]').first().click();
 page.once('dialog',d=>d.dismiss());await clickAdminAction(page,'[data-delete="991"]');assert.equal(inventory.length,1);assert.equal(calls.filter(m=>m==='DELETE').length,0);
 page.once('dialog',d=>d.accept());await clickAdminAction(page,'[data-delete="991"]');await page.locator('#status').filter({hasText:'Товар удалён'}).waitFor();assert.equal(inventory.length,0);
 inventory=[{...row,reserved:true}];await page.goto('http://localhost:8770/');await page.locator('[data-id="991"]').waitFor();assert.equal(await page.locator('.catalog-status').textContent(),'На брони');await page.locator('[data-id="991"]').click();assert.equal(await page.locator('[data-action=add-cart]').isDisabled(),true);await page.locator('[data-action=wishlist]').click();assert.equal(await page.locator('[data-action=wishlist]').getAttribute('aria-pressed'),'true');
 // A reservation placed after the item was added stops manager handoff.
 inventory=[{...row,reserved:false}];await page.reload();await page.locator('[data-id="991"]').click();await page.locator('[data-action=add-cart]').click();await page.locator('#backProduct').click();await page.locator('[data-tab=cart]').click();inventory=[{...row,reserved:true}];await page.locator('[data-cart-action=checkout]').click();await page.locator('#cartStatus').filter({hasText:'на брони'}).waitFor();assert.equal(await page.locator('[data-cart-action=plus]').isDisabled(),true);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.deepEqual(errors,[]);await page.close();console.log(width+' PASS reserve/release, visibility preserved, editor, cancel/confirm deletion, reserved storefront, wishlist, stale cart rejection, layout');
}
await browser.close();server.close()})().catch(e=>{console.error(e);server.close();process.exit(1)});
