const {clickAdminAction}=require('./admin-action-helper.cjs');
const {chromium}=require('playwright');
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http');
const root=path.resolve(__dirname,'..'),out=process.env.QA_OUTPUT||path.join(root,'browser-qa');fs.mkdirSync(out,{recursive:true});
const types={'.html':'text/html','.js':'text/javascript','.css':'text/css','.webp':'image/webp','.png':'image/png','.jpg':'image/jpeg','.woff2':'font/woff2','.ttf':'font/ttf'};
const server=http.createServer((req,res)=>{let file=path.join(root,decodeURIComponent(new URL(req.url,'http://localhost').pathname));if(file===root+path.sep)file=path.join(root,'index.html');if(!file.startsWith(root+path.sep)){res.writeHead(403).end();return}fs.readFile(file,(err,data)=>{res.writeHead(err?404:200,{'Content-Type':types[path.extname(file)]||'application/octet-stream'});res.end(err?'Missing':data)});});
(async()=>{
 await new Promise(r=>server.listen(8765,'127.0.0.1',r));const browser=await chromium.launch();
 const cfg={window:{}};require('node:vm').runInNewContext(fs.readFileSync(root+'/config.js','utf8'),cfg);
 const liveResponse=await fetch(cfg.window.STORE_CONFIG.url+'/rest/v1/products?select=id,brand,name,category,size,price,currency,image_url,photos,description,available,fulfillment_status,gender&available=eq.true',{headers:{apikey:cfg.window.STORE_CONFIG.key},signal:AbortSignal.timeout(20000)});
 assert.equal(liveResponse.status,200);const live=await liveResponse.json();assert.ok(live.length>0);assert.ok(live.every(p=>p.fulfillment_status==='in_stock'||p.fulfillment_status==='on_order'));
 for(const viewport of [{width:390,height:844},{width:400,height:620},{width:1280,height:900}]){
  const name=viewport.width===400?'telegram-desktop':viewport.width<800?'mobile':'desktop',context=await browser.newContext({viewport,isMobile:name==='mobile',hasTouch:name==='mobile'}),page=await context.newPage();context.setDefaultTimeout(15000);const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.addInitScript(()=>localStorage.setItem('jpAnalyticsConsent','declined'));await page.goto('http://127.0.0.1:8765/',{waitUntil:'domcontentloaded'});await page.locator('.product').first().waitFor();await page.evaluate(()=>document.fonts.ready);await page.screenshot({path:out+'/'+name+'-catalog.png',fullPage:false});
  assert.equal(await page.locator('.product').count(),live.length);
  await page.locator('#openCatalogMenu').click();await page.locator('[data-gender=men]').click();assert.equal(await page.locator('.product').count(),live.filter(p=>p.gender==='men'||p.gender==='unisex').length);await page.locator('[data-gender=women]').click();assert.equal(await page.locator('.product').count(),live.filter(p=>p.gender==='women'||p.gender==='unisex').length);await page.locator('#resetMenu').click();await page.locator('#showMenuProducts').click();
  const assertFits=async()=>assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Page overflows horizontally');await assertFits();
  await page.locator('[data-id="36"]').click();await page.locator('.hero img').waitFor();assert.ok(await page.locator('[data-related]').count()>0);assert.notEqual(await page.locator('[data-related]').first().getAttribute('data-related'),'36');await page.screenshot({path:out+'/'+name+'-single-size.png',fullPage:false});assert.equal(await page.locator('[data-size]').count(),0);await assertFits();await page.locator('#backProduct').click();
  // Fixture data stays in this browser; no catalogue writes or Telegram sends.
  let fresh={...live.find(p=>p.id===60),id:900001,size:'40; 41; 44.5',fulfillment_status:'on_order',description:'Первая строка\nВторая строка <script>не HTML</script>'};
  const accessory={...fresh,id:900003,category:'Аксессуары',size:'XL',gender:'unisex',fulfillment_status:'in_stock'};fresh={...fresh,gender:'men'};
  await page.route('**/rest/v1/products?**',route=>route.fulfill({json:route.request().url().includes('&id=eq.')?[fresh]:[fresh,accessory]}));let telegram=[];await page.addInitScript(()=>{window.open=url=>{window.__qaTelegram=url};});
  await page.reload({waitUntil:'domcontentloaded'});await page.locator('[data-id="900001"]').waitFor();await page.locator('#openCatalogMenu').click();await page.locator('[data-menu-type=category][data-menu-value="Аксессуары"]').click();assert.deepEqual(await page.locator('#menuChoices-size button').allTextContents(),['Все','XL']);await page.screenshot({path:out+'/'+name+'-catalog-menu.png',fullPage:false});await page.locator('[data-menu-type=size][data-menu-value=XL]').click();assert.equal(await page.locator('#showMenuProducts').innerText(),'Показать товары · 1');await page.locator('#resetMenu').click();await page.locator('[data-menu-group=fulfillment_status]').click();await page.locator('[data-menu-type=fulfillment_status][data-menu-value=on_order]').click();await page.locator('[data-menu-group=category]').click();await page.locator('[data-menu-type=category]').filter({hasText:fresh.category}).click();await page.locator('[data-menu-type=size][data-menu-value="41"]').click();await page.locator('#showMenuProducts').click();assert.equal(await page.locator('.product').count(),1);assert.equal(await page.locator('#openCatalogMenu').getAttribute('aria-expanded'),'false');
  await page.locator('[data-id="900001"]').click();assert.equal(await page.locator('[data-size]').count(),3);assert.equal(await page.locator('[data-size="41"]').getAttribute('aria-pressed'),'true');await assertFits();
  const boxes=await page.evaluate(()=>{const a=document.querySelector('.product-gallery').getBoundingClientRect(),b=document.querySelector('.detail').getBoundingClientRect();return {gallery:{x:a.x,y:a.y,width:a.width,height:a.height},detail:{x:b.x,y:b.y}}});assert.ok(name==='desktop'?boxes.detail.x>boxes.gallery.x+boxes.gallery.width-1:boxes.detail.y>=boxes.gallery.y+boxes.gallery.height-1);
  await page.screenshot({path:out+'/'+name+'-multiple-sizes.png',fullPage:true});assert.match(await page.locator('.purchase-note').innerText(),/10–14 рабочих дней/);assert.doesNotMatch(await page.locator('.detail').innerText(),/Артикул:/);assert.equal(await page.locator('.product-description').count(),1);assert.equal(await page.locator('.product-description').textContent(),fresh.description);assert.equal(await page.locator('#productContent script').count(),0);await page.locator('.product-sourcing').scrollIntoViewIfNeeded();assert.ok(await page.locator('.product-sourcing').isVisible());assert.match(await page.locator('.product-sourcing').innerText(),/Не нашли нужный размер/);
  fresh={...fresh,size:'40; 41'};
  // Cart and wishlist persist in the browser, while checkout revalidates current prices.
  await page.reload({waitUntil:'domcontentloaded'});await page.locator('[data-id="900001"]').waitFor();
  await page.locator('[data-heart="900001"]').click();await page.locator('[data-tab="favorites"]').click();assert.equal(await page.locator('#count').innerText(),'Виш-лист · 1');
  await page.locator('[data-id="900001"]').click();await page.locator('.cart-add').click();assert.match(await page.locator('#sizeHint').innerText(),/выберите/);
  assert.equal(await page.locator('.buy').count(),0);assert.equal(await page.locator('.detail-actions button').count(),2);assert.equal(await page.locator('.detail-wishlist svg').count(),1);assert.equal(await page.locator('.cart-add svg').count(),1);assert.equal(await page.locator('.cart-add').innerText(),'Купить');
  await page.locator('[data-size="40"]').click();await page.locator('.cart-add').click();await page.locator('.cart-add').click();await page.locator('[data-size="41"]').click();await page.locator('.cart-add').click();
  await page.locator('#backProduct').click();await page.locator('[data-tab="cart"]').click();assert.equal(await page.locator('#cartBadge').innerText(),'2');await page.waitForTimeout(370);await page.locator('[data-cart-action="plus"]').first().click();assert.equal(await page.locator('.cart-item').count(),2);assert.equal(await page.locator('#cartBadge').innerText(),'3');await assertFits();
  await page.reload({waitUntil:'domcontentloaded'});await page.locator('[data-id="900001"]').waitFor();await page.locator('[data-tab="cart"]').click();assert.equal(await page.locator('.cart-item').count(),2);assert.equal(await page.locator('#cartBadge').innerText(),'3');
  await page.locator('[data-cart-action="minus"]').first().click();assert.equal(await page.locator('#cartBadge').innerText(),'2');await page.waitForTimeout(370);await page.locator('[data-cart-action="plus"]').first().click();
  await page.evaluate(()=>{if(window.Telegram?.WebApp)window.Telegram.WebApp.openTelegramLink=url=>{window.__qaTelegram=url}});
  fresh={...fresh,price:Number(fresh.price)+1};await page.locator('[data-cart-action="checkout"]').click();await page.locator('#cartStatus').filter({hasText:'изменились'}).waitFor();assert.equal(await page.evaluate(()=>window.__qaTelegram),undefined);
  await page.locator('[data-cart-action="checkout"]').click();await page.locator('#cartStatus').filter({hasText:'Заказ подготовлен'}).waitFor();assert.match(decodeURIComponent(await page.evaluate(()=>window.__qaTelegram)),/размер 40 — 2 шт/);
  await assertFits();await page.screenshot({path:out+'/'+name+'-cart.png',fullPage:true});await page.locator('[data-cart-action="remove"]').first().click();assert.equal(await page.locator('.cart-item').count(),1);
  await page.locator('[data-tab="favorites"]').click();assert.equal(await page.locator('.product').count(),1);await page.screenshot({path:out+'/'+name+'-wishlist.png',fullPage:true});
  fresh={...fresh,fulfillment_status:'in_stock'};await page.reload({waitUntil:'domcontentloaded'});await page.locator('[data-id="900001"]').click();await page.locator('[data-size="40"]').click();await page.locator('.cart-add').click();await page.locator('.cart-add').click();assert.match(await page.locator('#shareStatus').innerText(),/уже в корзине/);assert.equal(await page.locator('#cartBadge').innerText(),'2');await page.locator('#backProduct').click();await page.locator('[data-tab="cart"]').click();assert.equal(await page.locator('[data-cart-action="plus"]:enabled').count(),0);
  await page.route('**/rest/v1/rpc/store_product_wishlist_counts',r=>r.fulfill({json:{days:30,counts:{}}}));
  await page.route('**/rest/v1/rpc/store_analytics_summary',r=>r.fulfill({json:{active:0,visitors:0}}));
  await page.goto('http://127.0.0.1:8765/admin.html',{waitUntil:'domcontentloaded'});await page.screenshot({path:out+'/'+name+'-admin-login.png',fullPage:true});await assertFits();
  // Render and exercise the real editor with a synthetic session/API response.
  let inventory=[{...live.find(p=>p.id===60),id:900002,size:'40; 41; 44.5',fulfillment_status:'on_order',gender:'men',revision:1}];
  await page.route('**/rest/v1/products?**',route=>{const req=route.request();if(req.method()==='PATCH'){inventory[0]={...inventory[0],...req.postDataJSON(),revision:inventory[0].revision+1};return route.fulfill({json:inventory})}return route.fulfill({json:inventory})});
  await page.evaluate(rows=>{session={access_token:'synthetic',expires_at:Date.now()/1000+3600,user:{id:'synthetic'}};items=rows;document.querySelector('#login').classList.add('hidden');document.querySelector('#workspace').classList.remove('hidden');render();},inventory);
  await assertFits();await page.screenshot({path:out+'/'+name+'-admin-inventory.png',fullPage:true});await clickAdminAction(page,'[data-edit="900002"]');assert.equal(await page.locator('[name="size"]').inputValue(),'40\n41\n44.5');assert.equal(await page.locator('[name="fulfillment_status"]').inputValue(),'on_order');await assertFits();await page.screenshot({path:out+'/'+name+'-admin-editor.png',fullPage:true});
  assert.equal(await page.locator('[name=gender]').inputValue(),'men');await page.locator('[name=gender]').selectOption('unisex');await page.locator('[name="size"]').fill('40\n44,5\n40');await page.locator('[name="fulfillment_status"]').selectOption('in_stock');await page.locator('#save').click();await page.locator('#status').filter({hasText:'Товар сохранён'}).waitFor();assert.equal(inventory[0].gender,'unisex');assert.equal(inventory[0].size,'40; 44.5');assert.equal(inventory[0].fulfillment_status,'in_stock');await clickAdminAction(page,'[data-edit="900002"]');assert.equal(await page.locator('[name="size"]').inputValue(),'40\n44.5');await page.locator('#cancel').click();await clickAdminAction(page,'[data-toggle="900002"]');assert.equal(inventory[0].available,false);assert.equal(inventory[0].fulfillment_status,'in_stock');
  assert.deepEqual(errors,[]);console.log(name+' PASS: live catalogue, decimal/single/multiple sizes, filters, selection, stale-size rejection, escaping, layouts, editor roundtrip, visibility');await context.close();
 }
 await browser.close();server.close();fs.writeFileSync(out+'/summary.json',JSON.stringify({liveProducts:live.length,viewports:[390,400,1280],result:'passed'},null,2));
})().catch(e=>{console.error(e);server.close();process.exit(1);});
